In [1]:
import pandas as pd
import numpy as np

In [2]:
df =pd.read_csv("BTC-USD.csv")

In [3]:
df

,Date,Open,High,Low,Close,Adj Close,Volume
0,2014-09-17,465.864014,468.174011,452.421997,457.334015,457.334015,21056800
1,2014-09-18,456.859985,456.859985,413.104004,424.440002,424.440002,34483200
2,2014-09-19,424.102997,427.834991,384.532013,394.795990,394.795990,37919700
3,2014-09-20,394.673004,423.295990,389.882996,408.903992,408.903992,36863600
4,2014-09-21,408.084991,412.425995,393.181000,398.821014,398.821014,26580100
...,...,...,...,...,...,...,...
2708,2022-02-15,42586.464844,44667.218750,42491.035156,44575.203125,44575.203125,22721659051
2709,2022-02-16,44578.277344,44578.277344,43456.691406,43961.859375,43961.859375,19792547657
2710,2022-02-17,43937.070313,44132.972656,40249.371094,40538.011719,40538.011719,26246662813
2711,2022-02-18,40552.132813,40929.152344,39637.617188,40030.976563,40030.976563,23310007704
2712,2022-02-19,40022.132813,40246.027344,40010.867188,40126.429688,40126.429688,22263900160

In [4]:
df2 =pd.read_csv("Amazon.csv")

In [5]:
df2

           Date       Close        High         Low        Open    Volume
0    2025-01-02  220.220001  225.149994  218.190002  222.029999  33956600
1    2025-01-03  224.190002  225.360001  221.619995  222.509995  27515600
2    2025-01-06  227.610001  228.839996  224.839996  226.779999  31849800
3    2025-01-07  222.110001  228.380005  221.460007  227.899994  28084200
4    2025-01-08  222.130005  223.520004  220.199997  223.190002  25033300
..          ...         ...         ...         ...         ...       ...
245  2025-12-24  232.380005  232.949997  231.330002  232.130005  11420500
246  2025-12-26  232.520004  232.990005  231.179993  232.039993  15994700
247  2025-12-29  232.070007  232.600006  230.770004  231.940002  19797900
248  2025-12-30  232.529999  232.770004  230.199997  231.210007  21910500
249  2025-12-31  230.820007  232.990005  230.119995  232.910004  24383700

[250 rows x 6 columns]

In [6]:
df3=pd.read_csv("exchange_rate_to_usd.csv")
df3

,date,chinese_yuan_to_usd,euro_to_usd,japanese_yen_to_usd,uk_pound_to_usd,us_dollar_to_usd,Unnamed: 6,australian_dollar_to_usd,bahrain_dinar_to_usd,Unnamed: 9,...,south_african_rand_to_usd,sri_lankan_rupee_to_usd,swedish_krona_to_usd,swiss_franc_to_usd,thai_baht_to_usd,trinidadian_dollar_to_usd,tunisian_dinar_to_usd,uae_dirham_to_usd,uruguayan_peso_to_usd,bolivar_fuerte_to_usd
0,02-01-2004,NaN,1.2592,NaN,1.78580,1,NaN,0.7527,2.659574,NaN,...,0.149813,0.010313,0.138889,NaN,NaN,NaN,NaN,0.272294,NaN,NaN
1,05-01-2004,0.120817,1.2657,0.009355,1.79960,1,NaN,0.7630,2.659574,NaN,...,0.157233,0.010277,0.139665,0.812876,0.025393,NaN,NaN,0.272294,NaN,NaN
2,06-01-2004,0.120815,1.2756,0.009412,1.82090,1,NaN,0.7668,2.659574,NaN,...,0.154440,0.010245,NaN,0.813008,0.025508,0.159727,NaN,0.272294,NaN,NaN
3,07-01-2004,0.120814,1.2679,0.009413,1.81400,1,NaN,0.7677,2.659574,NaN,...,NaN,NaN,0.139519,0.807363,0.025602,0.159393,NaN,0.272294,NaN,NaN
4,08-01-2004,0.120814,1.2634,0.009421,1.81220,1,NaN,0.7679,2.659574,NaN,...,0.150602,0.010222,0.138600,0.802053,0.025630,NaN,NaN,0.272294,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5536,14-01-2026,0.143406,1.1651,0.006281,1.34495,1,NaN,0.6697,NaN,NaN,...,NaN,NaN,0.108654,1.248439,0.031765,0.148041,NaN,0.272294,0.025850,NaN
5537,15-01-2026,0.143443,1.1624,0.006309,1.34185,1,NaN,0.6675,NaN,NaN,...,NaN,NaN,0.108651,1.248128,0.031760,0.148249,NaN,0.272294,0.025907,NaN
5538,16-01-2026,0.143507,1.1617,0.006321,1.34085,1,NaN,0.6707,NaN,NaN,...,NaN,NaN,0.108378,1.247816,0.031867,0.148196,NaN,NaN,0.026031,NaN
5539,20-01-2026,0.143666,1.1728,0.006323,1.34630,1,NaN,0.6738,NaN,NaN,...,NaN,NaN,NaN,1.266464,0.032098,0.148124,NaN,NaN,0.026166,NaN
5540,21-01-2026,0.143600,1.1739,0.006321,1.34085,1,NaN,0.6733,NaN,NaN,...,NaN,NaN,0.110112,1.264382,0.032219,0.147938,NaN,0.272294,0.026417,NaN

In [7]:
df4=pd.read_csv("gold_prices_10y.csv")
df4

,Date,Close,High,Low,Open,Volume,Adj Close,Daily_Return,MA_20,MA_50,MA_200,Volatility_20,Year,Month,Day_of_Week,Quarter
0,29-01-2016,106.949997,107.000000,106.260002,106.610001,8098700,106.949997,NaN,NaN,NaN,NaN,NaN,2016,1,4,1
1,01-02-2016,108.050003,108.150002,107.529999,107.540001,10471800,108.050003,1.028524,NaN,NaN,NaN,NaN,2016,2,0,1
2,02-02-2016,108.089996,108.180000,107.349998,107.919998,6656000,108.089996,0.037014,NaN,NaN,NaN,NaN,2016,2,1,1
3,03-02-2016,109.250000,109.580002,107.900002,107.910004,15785200,109.250000,1.073183,NaN,NaN,NaN,NaN,2016,2,2,1
4,04-02-2016,110.570000,110.699997,109.919998,110.449997,13213700,110.570000,1.208238,NaN,NaN,NaN,NaN,2016,2,3,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2506,16-01-2026,421.290008,424.799988,417.040008,422.799988,20951600,421.290008,-0.481888,410.588002,393.921000,339.46595,1.482148,2026,1,4,1
2507,20-01-2026,437.230011,438.140015,434.100006,436.690002,21308100,437.230011,3.783617,412.521002,395.335400,340.21130,1.670545,2026,1,1,1
2508,21-01-2026,443.600006,448.000000,437.109985,446.869995,38830200,443.600006,1.456898,414.750003,396.886000,340.99720,1.682109,2026,1,2,1
2509,22-01-2026,451.790008,452.980011,443.559998,443.839996,19251200,451.790008,1.846258,416.928003,398.555601,341.85755,1.659640,2026,1,3,1
2510,23-01-2026,458.000000,458.750000,453.450012,454.109985,21497000,458.000000,1.374530,419.146002,400.148001,342.77900,1.660933,2026,1,4,1

In [8]:
df5=pd.read_csv("NIFTY 100_15minute.csv")

In [9]:
df5

                      date      open      high       low     close  volume
0      2015-01-09 09:15:00   8300.60   8317.25   8300.60   8307.50       0
1      2015-01-09 09:30:00   8307.50   8308.55   8290.90   8297.00       0
2      2015-01-09 09:45:00   8298.30   8298.85   8288.25   8296.05       0
3      2015-01-09 10:00:00   8296.05   8300.65   8288.45   8294.75       0
4      2015-01-09 10:15:00   8294.75   8304.50   8292.00   8304.00       0
...                    ...       ...       ...       ...       ...     ...
68044  2026-01-22 16:45:00  25860.25  25860.25  25860.25  25860.25       0
68045  2026-01-22 17:00:00  25860.25  25860.25  25860.25  25860.25       0
68046  2026-01-22 17:15:00  25860.25  25860.25  25860.25  25860.25       0
68047  2026-01-22 17:30:00  25860.25  25860.25  25860.25  25860.25       0
68048  2026-01-22 17:45:00  25860.25  25860.25  25860.25  25860.25       0

[68049 rows x 6 columns]

In [10]:
df

,Date,Open,High,Low,Close,Adj Close,Volume
0,2014-09-17,465.864014,468.174011,452.421997,457.334015,457.334015,21056800
1,2014-09-18,456.859985,456.859985,413.104004,424.440002,424.440002,34483200
2,2014-09-19,424.102997,427.834991,384.532013,394.795990,394.795990,37919700
3,2014-09-20,394.673004,423.295990,389.882996,408.903992,408.903992,36863600
4,2014-09-21,408.084991,412.425995,393.181000,398.821014,398.821014,26580100
...,...,...,...,...,...,...,...
2708,2022-02-15,42586.464844,44667.218750,42491.035156,44575.203125,44575.203125,22721659051
2709,2022-02-16,44578.277344,44578.277344,43456.691406,43961.859375,43961.859375,19792547657
2710,2022-02-17,43937.070313,44132.972656,40249.371094,40538.011719,40538.011719,26246662813
2711,2022-02-18,40552.132813,40929.152344,39637.617188,40030.976563,40030.976563,23310007704
2712,2022-02-19,40022.132813,40246.027344,40010.867188,40126.429688,40126.429688,22263900160

In [11]:
#eda

In [12]:
df = df.drop('Adj Close', axis=1)
df

,Date,Open,High,Low,Close,Volume
0,2014-09-17,465.864014,468.174011,452.421997,457.334015,21056800
1,2014-09-18,456.859985,456.859985,413.104004,424.440002,34483200
2,2014-09-19,424.102997,427.834991,384.532013,394.795990,37919700
3,2014-09-20,394.673004,423.295990,389.882996,408.903992,36863600
4,2014-09-21,408.084991,412.425995,393.181000,398.821014,26580100
...,...,...,...,...,...,...
2708,2022-02-15,42586.464844,44667.218750,42491.035156,44575.203125,22721659051
2709,2022-02-16,44578.277344,44578.277344,43456.691406,43961.859375,19792547657
2710,2022-02-17,43937.070313,44132.972656,40249.371094,40538.011719,26246662813
2711,2022-02-18,40552.132813,40929.152344,39637.617188,40030.976563,23310007704
2712,2022-02-19,40022.132813,40246.027344,40010.867188,40126.429688,22263900160

In [13]:
df = df.rename(columns={
    'Open': 'Open_Price',
    'High': 'High_Price',
    'Low': 'Low_Price',
    'Close': 'Close_Price'
})

In [14]:
df

,Date,Open_Price,High_Price,Low_Price,Close_Price,Volume
0,2014-09-17,465.864014,468.174011,452.421997,457.334015,21056800
1,2014-09-18,456.859985,456.859985,413.104004,424.440002,34483200
2,2014-09-19,424.102997,427.834991,384.532013,394.795990,37919700
3,2014-09-20,394.673004,423.295990,389.882996,408.903992,36863600
4,2014-09-21,408.084991,412.425995,393.181000,398.821014,26580100
...,...,...,...,...,...,...
2708,2022-02-15,42586.464844,44667.218750,42491.035156,44575.203125,22721659051
2709,2022-02-16,44578.277344,44578.277344,43456.691406,43961.859375,19792547657
2710,2022-02-17,43937.070313,44132.972656,40249.371094,40538.011719,26246662813
2711,2022-02-18,40552.132813,40929.152344,39637.617188,40030.976563,23310007704
2712,2022-02-19,40022.132813,40246.027344,40010.867188,40126.429688,22263900160

In [15]:
df["Asset_Name"] = "Bitcoin"
df["Asset_Type"] = "Crypto"
df["Sector"] = "Cryptocurrency"
df

,Date,Open_Price,High_Price,Low_Price,Close_Price,Volume,Asset_Name,Asset_Type,Sector
0,2014-09-17,465.864014,468.174011,452.421997,457.334015,21056800,Bitcoin,Crypto,Cryptocurrency
1,2014-09-18,456.859985,456.859985,413.104004,424.440002,34483200,Bitcoin,Crypto,Cryptocurrency
2,2014-09-19,424.102997,427.834991,384.532013,394.795990,37919700,Bitcoin,Crypto,Cryptocurrency
3,2014-09-20,394.673004,423.295990,389.882996,408.903992,36863600,Bitcoin,Crypto,Cryptocurrency
4,2014-09-21,408.084991,412.425995,393.181000,398.821014,26580100,Bitcoin,Crypto,Cryptocurrency
...,...,...,...,...,...,...,...,...,...
2708,2022-02-15,42586.464844,44667.218750,42491.035156,44575.203125,22721659051,Bitcoin,Crypto,Cryptocurrency
2709,2022-02-16,44578.277344,44578.277344,43456.691406,43961.859375,19792547657,Bitcoin,Crypto,Cryptocurrency
2710,2022-02-17,43937.070313,44132.972656,40249.371094,40538.011719,26246662813,Bitcoin,Crypto,Cryptocurrency
2711,2022-02-18,40552.132813,40929.152344,39637.617188,40030.976563,23310007704,Bitcoin,Crypto,Cryptocurrency
2712,2022-02-19,40022.132813,40246.027344,40010.867188,40126.429688,22263900160,Bitcoin,Crypto,Cryptocurrency

In [16]:
#df3=exchang rate

In [17]:
df3

,date,chinese_yuan_to_usd,euro_to_usd,japanese_yen_to_usd,uk_pound_to_usd,us_dollar_to_usd,Unnamed: 6,australian_dollar_to_usd,bahrain_dinar_to_usd,Unnamed: 9,...,south_african_rand_to_usd,sri_lankan_rupee_to_usd,swedish_krona_to_usd,swiss_franc_to_usd,thai_baht_to_usd,trinidadian_dollar_to_usd,tunisian_dinar_to_usd,uae_dirham_to_usd,uruguayan_peso_to_usd,bolivar_fuerte_to_usd
0,02-01-2004,NaN,1.2592,NaN,1.78580,1,NaN,0.7527,2.659574,NaN,...,0.149813,0.010313,0.138889,NaN,NaN,NaN,NaN,0.272294,NaN,NaN
1,05-01-2004,0.120817,1.2657,0.009355,1.79960,1,NaN,0.7630,2.659574,NaN,...,0.157233,0.010277,0.139665,0.812876,0.025393,NaN,NaN,0.272294,NaN,NaN
2,06-01-2004,0.120815,1.2756,0.009412,1.82090,1,NaN,0.7668,2.659574,NaN,...,0.154440,0.010245,NaN,0.813008,0.025508,0.159727,NaN,0.272294,NaN,NaN
3,07-01-2004,0.120814,1.2679,0.009413,1.81400,1,NaN,0.7677,2.659574,NaN,...,NaN,NaN,0.139519,0.807363,0.025602,0.159393,NaN,0.272294,NaN,NaN
4,08-01-2004,0.120814,1.2634,0.009421,1.81220,1,NaN,0.7679,2.659574,NaN,...,0.150602,0.010222,0.138600,0.802053,0.025630,NaN,NaN,0.272294,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5536,14-01-2026,0.143406,1.1651,0.006281,1.34495,1,NaN,0.6697,NaN,NaN,...,NaN,NaN,0.108654,1.248439,0.031765,0.148041,NaN,0.272294,0.025850,NaN
5537,15-01-2026,0.143443,1.1624,0.006309,1.34185,1,NaN,0.6675,NaN,NaN,...,NaN,NaN,0.108651,1.248128,0.031760,0.148249,NaN,0.272294,0.025907,NaN
5538,16-01-2026,0.143507,1.1617,0.006321,1.34085,1,NaN,0.6707,NaN,NaN,...,NaN,NaN,0.108378,1.247816,0.031867,0.148196,NaN,NaN,0.026031,NaN
5539,20-01-2026,0.143666,1.1728,0.006323,1.34630,1,NaN,0.6738,NaN,NaN,...,NaN,NaN,NaN,1.266464,0.032098,0.148124,NaN,NaN,0.026166,NaN
5540,21-01-2026,0.143600,1.1739,0.006321,1.34085,1,NaN,0.6733,NaN,NaN,...,NaN,NaN,0.110112,1.264382,0.032219,0.147938,NaN,0.272294,0.026417,NaN

In [18]:
cols_to_drop = [
    "australian_dollar_to_usd", "Unnamed: 6", "bahrain_dinar_to_usd", 
    "Unnamed: 9", "south_african_rand_to_usd", "sri_lankan_rupee_to_usd", 
    "thai_baht_to_usd", "trinidadian_dollar_to_usd", "tunisian_dinar_to_usd", 
    "uae_dirham_to_usd", "uruguayan_peso_to_usd", "bolivar_fuerte_to_usd",
    "brazilian_real_to_usd", "brunei_dollar_to_usd", "canadian_dollar_to_usd", 
    "chilean_peso_to_usd", "pakistani_rupee_to_usd", "peruvian_sol_to_usd", 
    "philippine_peso_to_usd", "polish_zloty_to_usd", "qatari_riyal_to_usd", 
    "russian_ruble_to_usd", "saudi_arabian_riyal_to_usd", "singapore_dollar_to_usd", 
    "swedish_krona_to_usd", "swiss_franc_to_usd"
]


df3 = df3.drop(columns=cols_to_drop)


print(f"New shape: {df3.shape}")
df3.head()

New shape: (5541, 26)

,date,chinese_yuan_to_usd,euro_to_usd,japanese_yen_to_usd,uk_pound_to_usd,us_dollar_to_usd,colombian_peso_to_usd,czech_koruna_to_usd,danish_krone_to_usd,hungarian_forint_to_usd,...,korean_won_to_usd,kuwaiti_dinar_to_usd,libyan_dinar_to_usd,malaysian_ringgit_to_usd,mauritian_rupee_to_usd,mexican_peso_to_usd,nepalese_rupee_to_usd,new_zealand_dollar_to_usd,norwegian_krone_to_usd,omani_rial_to_usd
0,02-01-2004,NaN,1.2592,NaN,1.7858,1,0.000360,0.038864,0.169130,NaN,...,0.000837,NaN,NaN,NaN,NaN,0.090184,0.013506,NaN,0.150022,2.60078
1,05-01-2004,0.120817,1.2657,0.009355,1.7996,1,0.000360,0.039101,0.169952,0.004835,...,0.000836,NaN,0.5175,0.263158,0.038446,NaN,0.013506,0.66330,0.150571,2.60078
2,06-01-2004,0.120815,1.2756,0.009412,1.8209,1,0.000360,0.039396,0.171280,0.004904,...,NaN,3.393281,0.5175,0.263158,0.038517,0.091169,0.013506,0.66925,0.148914,2.60078
3,07-01-2004,0.120814,1.2679,0.009413,1.8140,1,0.000362,0.039177,0.170242,0.004833,...,0.000842,3.393281,0.5175,0.263158,0.038734,0.091706,0.013506,0.66860,0.147955,2.60078
4,08-01-2004,0.120814,1.2634,0.009421,1.8122,1,0.000362,0.039035,0.169627,0.004772,...,0.000842,3.393281,0.5175,0.263158,0.038744,0.091872,0.013506,0.67040,NaN,2.60078

In [19]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5541 entries, 0 to 5540
Data columns (total 26 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   date                       5541 non-null   object
 1   chinese_yuan_to_usd        5144 non-null   float64
 2   euro_to_usd                5469 non-null   float64
 3   japanese_yen_to_usd        5237 non-null   float64
 4   uk_pound_to_usd            5442 non-null   float64
 5   us_dollar_to_usd           5541 non-null   int64
 6   colombian_peso_to_usd      4058 non-null   float64
 7   czech_koruna_to_usd        5314 non-null   float64
 8   danish_krone_to_usd        5281 non-null   float64
 9   hungarian_forint_to_usd    3641 non-null   float64
 10  icelandic_krona_to_usd     3669 non-null   float64
 11  indian_rupee_to_usd        5080 non-null   float64
 12  indonesian_rupiah_to_usd   3540 non-null   float64
 13  iranian_rial_to_usd        2762 non-null   float64
 14  israeli_new_shekel_to_usd  5136 non-null   float64
 15  kazakhstani_tenge_to_usd   3099 non-null   float64
 16  korean_won_to_usd          5169 non-null   float64
 17  kuwaiti_dinar_to_usd       4657 non-null   float64
 18  libyan_dinar_to_usd        3760 non-null   float64
 19  malaysian_ringgit_to_usd   5172 non-null   float64
 20  mauritian_rupee_to_usd     5036 non-null   float64
 21  mexican_peso_to_usd        5079 non-null   float64
 22  nepalese_rupee_to_usd      3512 non-null   float64
 23  new_zealand_dollar_to_usd  5293 non-null   float64
 24  norwegian_krone_to_usd     5254 non-null   float64
 25  omani_rial_to_usd          5096 non-null   float64
dtypes: float64(24), int64(1), object(1)
memory usage: 1.1+ MB

In [20]:
cols_to_drop = [
    "colombian_peso_to_usd",	"czech_koruna_to_usd",	"danish_krone_to_usd",	"hungarian_forint_to_usd",		"korean_won_to_usd",	"kuwaiti_dinar_to_usd",	"libyan_dinar_to_usd",	"malaysian_ringgit_to_usd"	,"mauritian_rupee_to_usd"	,"mexican_peso_to_usd",	"nepalese_rupee_to_usd"	,"new_zealand_dollar_to_usd"	,"norwegian_krone_to_usd",	"omani_rial_to_usd"
]


df3 = df3.drop(columns=cols_to_drop)


print(f"New shape: {df3.shape}")
df3.head()

New shape: (5541, 12)

,date,chinese_yuan_to_usd,euro_to_usd,japanese_yen_to_usd,uk_pound_to_usd,us_dollar_to_usd,icelandic_krona_to_usd,indian_rupee_to_usd,indonesian_rupiah_to_usd,iranian_rial_to_usd,israeli_new_shekel_to_usd,kazakhstani_tenge_to_usd
0,02-01-2004,NaN,1.2592,NaN,1.7858,1,NaN,0.021935,NaN,0.000120,NaN,NaN
1,05-01-2004,0.120817,1.2657,0.009355,1.7996,1,0.014229,0.021920,0.000119,0.000121,NaN,NaN
2,06-01-2004,0.120815,1.2756,0.009412,1.8209,1,0.014391,0.021920,0.000120,0.000121,0.228781,NaN
3,07-01-2004,0.120814,1.2679,0.009413,1.8140,1,0.014292,0.021915,0.000120,0.000120,0.227531,NaN
4,08-01-2004,0.120814,1.2634,0.009421,1.8122,1,0.014209,0.021959,0.000120,0.000120,0.227583,NaN

In [21]:
df3.isnull().sum()

date                            0
chinese_yuan_to_usd           397
euro_to_usd                    72
japanese_yen_to_usd           304
uk_pound_to_usd                99
us_dollar_to_usd                0
icelandic_krona_to_usd       1872
indian_rupee_to_usd           461
indonesian_rupiah_to_usd     2001
iranian_rial_to_usd          2779
israeli_new_shekel_to_usd     405
kazakhstani_tenge_to_usd     2442
dtype: int64

In [22]:
df3.rename(columns={"value": "Close_Price"}, inplace=True)
df3

,date,chinese_yuan_to_usd,euro_to_usd,japanese_yen_to_usd,uk_pound_to_usd,us_dollar_to_usd,icelandic_krona_to_usd,indian_rupee_to_usd,indonesian_rupiah_to_usd,iranian_rial_to_usd,israeli_new_shekel_to_usd,kazakhstani_tenge_to_usd
0,02-01-2004,NaN,1.2592,NaN,1.78580,1,NaN,0.021935,NaN,0.000120,NaN,NaN
1,05-01-2004,0.120817,1.2657,0.009355,1.79960,1,0.014229,0.021920,0.000119,0.000121,NaN,NaN
2,06-01-2004,0.120815,1.2756,0.009412,1.82090,1,0.014391,0.021920,0.000120,0.000121,0.228781,NaN
3,07-01-2004,0.120814,1.2679,0.009413,1.81400,1,0.014292,0.021915,0.000120,0.000120,0.227531,NaN
4,08-01-2004,0.120814,1.2634,0.009421,1.81220,1,0.014209,0.021959,0.000120,0.000120,0.227583,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
5536,14-01-2026,0.143406,1.1651,0.006281,1.34495,1,NaN,0.011086,NaN,NaN,0.317360,NaN
5537,15-01-2026,0.143443,1.1624,0.006309,1.34185,1,NaN,NaN,NaN,NaN,0.316857,NaN
5538,16-01-2026,0.143507,1.1617,0.006321,1.34085,1,NaN,0.011031,NaN,NaN,0.318674,NaN
5539,20-01-2026,0.143666,1.1728,0.006323,1.34630,1,NaN,0.010985,NaN,NaN,0.315856,NaN
5540,21-01-2026,0.143600,1.1739,0.006321,1.34085,1,NaN,0.010923,NaN,NaN,0.315060,NaN

In [23]:
df3

,date,chinese_yuan_to_usd,euro_to_usd,japanese_yen_to_usd,uk_pound_to_usd,us_dollar_to_usd,icelandic_krona_to_usd,indian_rupee_to_usd,indonesian_rupiah_to_usd,iranian_rial_to_usd,israeli_new_shekel_to_usd,kazakhstani_tenge_to_usd
0,02-01-2004,NaN,1.2592,NaN,1.78580,1,NaN,0.021935,NaN,0.000120,NaN,NaN
1,05-01-2004,0.120817,1.2657,0.009355,1.79960,1,0.014229,0.021920,0.000119,0.000121,NaN,NaN
2,06-01-2004,0.120815,1.2756,0.009412,1.82090,1,0.014391,0.021920,0.000120,0.000121,0.228781,NaN
3,07-01-2004,0.120814,1.2679,0.009413,1.81400,1,0.014292,0.021915,0.000120,0.000120,0.227531,NaN
4,08-01-2004,0.120814,1.2634,0.009421,1.81220,1,0.014209,0.021959,0.000120,0.000120,0.227583,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
5536,14-01-2026,0.143406,1.1651,0.006281,1.34495,1,NaN,0.011086,NaN,NaN,0.317360,NaN
5537,15-01-2026,0.143443,1.1624,0.006309,1.34185,1,NaN,NaN,NaN,NaN,0.316857,NaN
5538,16-01-2026,0.143507,1.1617,0.006321,1.34085,1,NaN,0.011031,NaN,NaN,0.318674,NaN
5539,20-01-2026,0.143666,1.1728,0.006323,1.34630,1,NaN,0.010985,NaN,NaN,0.315856,NaN
5540,21-01-2026,0.143600,1.1739,0.006321,1.34085,1,NaN,0.010923,NaN,NaN,0.315060,NaN

In [24]:
df3_long = df3.melt(
    id_vars=["date"],            
    var_name="Asset_Name",         
    value_name="Close_Price"       
)

In [25]:
df3_long.rename(columns={"date": "Date"}, inplace=True)

In [26]:
df3_long["Asset_Name"] = df3_long["Asset_Name"].str.replace("_to_usd", "")
df3_long["Asset_Name"] = df3_long["Asset_Name"].str.replace("_", " ")

In [27]:
df3_long["Asset_Type"] = "Forex"
df3_long["Sector"] = "Currency"

In [28]:
df3_long["Open_Price"] = df3_long["Close_Price"]
df3_long["High_Price"] = df3_long["Close_Price"]
df3_long["Low_Price"] = df3_long["Close_Price"]
df3_long["Volume"] = 0

In [29]:
df3_long

,Date,Asset_Name,Close_Price,Asset_Type,Sector,Open_Price,High_Price,Low_Price,Volume
0,02-01-2004,chinese yuan,NaN,Forex,Currency,NaN,NaN,NaN,0
1,05-01-2004,chinese yuan,0.120817,Forex,Currency,0.120817,0.120817,0.120817,0
2,06-01-2004,chinese yuan,0.120815,Forex,Currency,0.120815,0.120815,0.120815,0
3,07-01-2004,chinese yuan,0.120814,Forex,Currency,0.120814,0.120814,0.120814,0
4,08-01-2004,chinese yuan,0.120814,Forex,Currency,0.120814,0.120814,0.120814,0
...,...,...,...,...,...,...,...,...,...
60946,14-01-2026,kazakhstani tenge,NaN,Forex,Currency,NaN,NaN,NaN,0
60947,15-01-2026,kazakhstani tenge,NaN,Forex,Currency,NaN,NaN,NaN,0
60948,16-01-2026,kazakhstani tenge,NaN,Forex,Currency,NaN,NaN,NaN,0
60949,20-01-2026,kazakhstani tenge,NaN,Forex,Currency,NaN,NaN,NaN,0
60950,21-01-2026,kazakhstani tenge,NaN,Forex,Currency,NaN,NaN,NaN,0

In [30]:
#df4 =gold df

In [31]:
df4

,Date,Close,High,Low,Open,Volume,Adj Close,Daily_Return,MA_20,MA_50,MA_200,Volatility_20,Year,Month,Day_of_Week,Quarter
0,29-01-2016,106.949997,107.000000,106.260002,106.610001,8098700,106.949997,NaN,NaN,NaN,NaN,NaN,2016,1,4,1
1,01-02-2016,108.050003,108.150002,107.529999,107.540001,10471800,108.050003,1.028524,NaN,NaN,NaN,NaN,2016,2,0,1
2,02-02-2016,108.089996,108.180000,107.349998,107.919998,6656000,108.089996,0.037014,NaN,NaN,NaN,NaN,2016,2,1,1
3,03-02-2016,109.250000,109.580002,107.900002,107.910004,15785200,109.250000,1.073183,NaN,NaN,NaN,NaN,2016,2,2,1
4,04-02-2016,110.570000,110.699997,109.919998,110.449997,13213700,110.570000,1.208238,NaN,NaN,NaN,NaN,2016,2,3,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2506,16-01-2026,421.290008,424.799988,417.040008,422.799988,20951600,421.290008,-0.481888,410.588002,393.921000,339.46595,1.482148,2026,1,4,1
2507,20-01-2026,437.230011,438.140015,434.100006,436.690002,21308100,437.230011,3.783617,412.521002,395.335400,340.21130,1.670545,2026,1,1,1
2508,21-01-2026,443.600006,448.000000,437.109985,446.869995,38830200,443.600006,1.456898,414.750003,396.886000,340.99720,1.682109,2026,1,2,1
2509,22-01-2026,451.790008,452.980011,443.559998,443.839996,19251200,451.790008,1.846258,416.928003,398.555601,341.85755,1.659640,2026,1,3,1
2510,23-01-2026,458.000000,458.750000,453.450012,454.109985,21497000,458.000000,1.374530,419.146002,400.148001,342.77900,1.660933,2026,1,4,1

In [32]:
cols_to_drop1 = [
    "Adj Close","MA_20",	"MA_50",	"MA_200","Year","Month","Day_of_Week",	"Quarter"
]

# Dropping the columns
df4 = df4.drop(columns=cols_to_drop1)

# Checking the new shape to confirm they are gone
print(f"New shape: {df4.shape}")
df4.head()

New shape: (2511, 8)

,Date,Close,High,Low,Open,Volume,Daily_Return,Volatility_20
0,29-01-2016,106.949997,107.000000,106.260002,106.610001,8098700,NaN,NaN
1,01-02-2016,108.050003,108.150002,107.529999,107.540001,10471800,1.028524,NaN
2,02-02-2016,108.089996,108.180000,107.349998,107.919998,6656000,0.037014,NaN
3,03-02-2016,109.250000,109.580002,107.900002,107.910004,15785200,1.073183,NaN
4,04-02-2016,110.570000,110.699997,109.919998,110.449997,13213700,1.208238,NaN

In [33]:
df4.rename(columns={
    "Open": "Open_Price",
    "High": "High_Price",
    "Low": "Low_Price",
    "Close": "Close_Price",
    "Volatility_20": "Volatility"
}, inplace=True)

In [34]:
df4["Asset_Name"] = "Gold"
df4["Asset_Type"] = "Commodity"
df4["Sector"] = "Precious Metal"

In [35]:
df4

,Date,Close_Price,High_Price,Low_Price,Open_Price,Volume,Daily_Return,Volatility,Asset_Name,Asset_Type,Sector
0,29-01-2016,106.949997,107.000000,106.260002,106.610001,8098700,NaN,NaN,Gold,Commodity,Precious Metal
1,01-02-2016,108.050003,108.150002,107.529999,107.540001,10471800,1.028524,NaN,Gold,Commodity,Precious Metal
2,02-02-2016,108.089996,108.180000,107.349998,107.919998,6656000,0.037014,NaN,Gold,Commodity,Precious Metal
3,03-02-2016,109.250000,109.580002,107.900002,107.910004,15785200,1.073183,NaN,Gold,Commodity,Precious Metal
4,04-02-2016,110.570000,110.699997,109.919998,110.449997,13213700,1.208238,NaN,Gold,Commodity,Precious Metal
...,...,...,...,...,...,...,...,...,...,...,...
2506,16-01-2026,421.290008,424.799988,417.040008,422.799988,20951600,-0.481888,1.482148,Gold,Commodity,Precious Metal
2507,20-01-2026,437.230011,438.140015,434.100006,436.690002,21308100,3.783617,1.670545,Gold,Commodity,Precious Metal
2508,21-01-2026,443.600006,448.000000,437.109985,446.869995,38830200,1.456898,1.682109,Gold,Commodity,Precious Metal
2509,22-01-2026,451.790008,452.980011,443.559998,443.839996,19251200,1.846258,1.659640,Gold,Commodity,Precious Metal
2510,23-01-2026,458.000000,458.750000,453.450012,454.109985,21497000,1.374530,1.660933,Gold,Commodity,Precious Metal

In [36]:
df5

                      date      open      high       low     close  volume
0      2015-01-09 09:15:00   8300.60   8317.25   8300.60   8307.50       0
1      2015-01-09 09:30:00   8307.50   8308.55   8290.90   8297.00       0
2      2015-01-09 09:45:00   8298.30   8298.85   8288.25   8296.05       0
3      2015-01-09 10:00:00   8296.05   8300.65   8288.45   8294.75       0
4      2015-01-09 10:15:00   8294.75   8304.50   8292.00   8304.00       0
...                    ...       ...       ...       ...       ...     ...
68044  2026-01-22 16:45:00  25860.25  25860.25  25860.25  25860.25       0
68045  2026-01-22 17:00:00  25860.25  25860.25  25860.25  25860.25       0
68046  2026-01-22 17:15:00  25860.25  25860.25  25860.25  25860.25       0
68047  2026-01-22 17:30:00  25860.25  25860.25  25860.25  25860.25       0
68048  2026-01-22 17:45:00  25860.25  25860.25  25860.25  25860.25       0

[68049 rows x 6 columns]

In [37]:
#df5 nfti

In [38]:
df5.rename(columns={
    "open": "Open_Price",
    "high": "High_Price",
    "low": "Low_Price",
    "close": "Close_Price",
    "volume": "Volume"
}, inplace=True)

In [39]:
df5["Asset_Name"] = "BankNifty"   
df5["Asset_Type"] = "Index"            
df5["Sector"] = "Market Index"

In [40]:
df5

,date,Open_Price,High_Price,Low_Price,Close_Price,Volume,Asset_Name,Asset_Type,Sector
0,2015-01-09 09:15:00,8300.60,8317.25,8300.60,8307.50,0,BankNifty,Index,Market Index
1,2015-01-09 09:30:00,8307.50,8308.55,8290.90,8297.00,0,BankNifty,Index,Market Index
2,2015-01-09 09:45:00,8298.30,8298.85,8288.25,8296.05,0,BankNifty,Index,Market Index
3,2015-01-09 10:00:00,8296.05,8300.65,8288.45,8294.75,0,BankNifty,Index,Market Index
4,2015-01-09 10:15:00,8294.75,8304.50,8292.00,8304.00,0,BankNifty,Index,Market Index
...,...,...,...,...,...,...,...,...,...
68044,2026-01-22 16:45:00,25860.25,25860.25,25860.25,25860.25,0,BankNifty,Index,Market Index
68045,2026-01-22 17:00:00,25860.25,25860.25,25860.25,25860.25,0,BankNifty,Index,Market Index
68046,2026-01-22 17:15:00,25860.25,25860.25,25860.25,25860.25,0,BankNifty,Index,Market Index
68047,2026-01-22 17:30:00,25860.25,25860.25,25860.25,25860.25,0,BankNifty,Index,Market Index
68048,2026-01-22 17:45:00,25860.25,25860.25,25860.25,25860.25,0,BankNifty,Index,Market Index

In [41]:
df5.isnull().sum()

date           0
Open_Price     0
High_Price     0
Low_Price      0
Close_Price    0
Volume         0
Asset_Name     0
Asset_Type     0
Sector         0
dtype: int64

In [42]:
df4.isnull().sum()

Date             0
Close_Price      0
High_Price       0
Low_Price        0
Open_Price       0
Volume           0
Daily_Return     1
Volatility      20
Asset_Name       0
Asset_Type       0
Sector           0
dtype: int64

In [43]:
df3.isnull().sum()

date                            0
chinese_yuan_to_usd           397
euro_to_usd                    72
japanese_yen_to_usd           304
uk_pound_to_usd                99
us_dollar_to_usd                0
icelandic_krona_to_usd       1872
indian_rupee_to_usd           461
indonesian_rupiah_to_usd     2001
iranian_rial_to_usd          2779
israeli_new_shekel_to_usd     405
kazakhstani_tenge_to_usd     2442
dtype: int64

In [44]:
df2.isnull().sum()

Date      0
Close     0
High      0
Low       0
Open      0
Volume    0
dtype: int64

In [45]:
df.isnull().sum()

Date           0
Open_Price     0
High_Price     0
Low_Price      0
Close_Price    0
Volume         0
Asset_Name     0
Asset_Type     0
Sector         0
dtype: int64

In [46]:
df3

,date,chinese_yuan_to_usd,euro_to_usd,japanese_yen_to_usd,uk_pound_to_usd,us_dollar_to_usd,icelandic_krona_to_usd,indian_rupee_to_usd,indonesian_rupiah_to_usd,iranian_rial_to_usd,israeli_new_shekel_to_usd,kazakhstani_tenge_to_usd
0,02-01-2004,NaN,1.2592,NaN,1.78580,1,NaN,0.021935,NaN,0.000120,NaN,NaN
1,05-01-2004,0.120817,1.2657,0.009355,1.79960,1,0.014229,0.021920,0.000119,0.000121,NaN,NaN
2,06-01-2004,0.120815,1.2756,0.009412,1.82090,1,0.014391,0.021920,0.000120,0.000121,0.228781,NaN
3,07-01-2004,0.120814,1.2679,0.009413,1.81400,1,0.014292,0.021915,0.000120,0.000120,0.227531,NaN
4,08-01-2004,0.120814,1.2634,0.009421,1.81220,1,0.014209,0.021959,0.000120,0.000120,0.227583,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
5536,14-01-2026,0.143406,1.1651,0.006281,1.34495,1,NaN,0.011086,NaN,NaN,0.317360,NaN
5537,15-01-2026,0.143443,1.1624,0.006309,1.34185,1,NaN,NaN,NaN,NaN,0.316857,NaN
5538,16-01-2026,0.143507,1.1617,0.006321,1.34085,1,NaN,0.011031,NaN,NaN,0.318674,NaN
5539,20-01-2026,0.143666,1.1728,0.006323,1.34630,1,NaN,0.010985,NaN,NaN,0.315856,NaN
5540,21-01-2026,0.143600,1.1739,0.006321,1.34085,1,NaN,0.010923,NaN,NaN,0.315060,NaN

In [47]:
mean_value = df3['chinese_yuan_to_usd'].mean()
df3['chinese_yuan_to_usd'] = df3['chinese_yuan_to_usd'].fillna(mean_value)

In [48]:
df3.isnull().sum()

date                            0
chinese_yuan_to_usd             0
euro_to_usd                    72
japanese_yen_to_usd           304
uk_pound_to_usd                99
us_dollar_to_usd                0
icelandic_krona_to_usd       1872
indian_rupee_to_usd           461
indonesian_rupiah_to_usd     2001
iranian_rial_to_usd          2779
israeli_new_shekel_to_usd     405
kazakhstani_tenge_to_usd     2442
dtype: int64

In [49]:
mean_value = df3['chinese_yuan_to_usd'].mean()
df3['chinese_yuan_to_usd'] = df3['chinese_yuan_to_usd'].fillna(mean_value)

mean_value = df3['euro_to_usd'].mean()
df3['euro_to_usd'] = df3['euro_to_usd'].fillna(mean_value)

mean_value = df3['japanese_yen_to_usd'].mean()
df3['japanese_yen_to_usd'] = df3['japanese_yen_to_usd'].fillna(mean_value)

mean_value = df3['uk_pound_to_usd'].mean()
df3['uk_pound_to_usd'] = df3['uk_pound_to_usd'].fillna(mean_value)

mean_value = df3['us_dollar_to_usd'].mean()
df3['us_dollar_to_usd'] = df3['us_dollar_to_usd'].fillna(mean_value)

mean_value = df3['colombian_peso_to_usd'].mean()
df3['colombian_peso_to_usd'] = df3['colombian_peso_to_usd'].fillna(mean_value)

mean_value = df3['czech_koruna_to_usd'].mean()
df3['czech_koruna_to_usd'] = df3['czech_koruna_to_usd'].fillna(mean_value)

mean_value = df3['danish_krone_to_usd'].mean()
df3['danish_krone_to_usd'] = df3['danish_krone_to_usd'].fillna(mean_value)

mean_value = df3['hungarian_forint_to_usd'].mean()
df3['hungarian_forint_to_usd'] = df3['hungarian_forint_to_usd'].fillna(mean_value)

mean_value = df3['icelandic_krona_to_usd'].mean()
df3['icelandic_krona_to_usd'] = df3['icelandic_krona_to_usd'].fillna(mean_value)

mean_value = df3['indian_rupee_to_usd'].mean()
df3['indian_rupee_to_usd'] = df3['indian_rupee_to_usd'].fillna(mean_value)

mean_value = df3['indonesian_rupiah_to_usd'].mean()
df3['indonesian_rupiah_to_usd'] = df3['indonesian_rupiah_to_usd'].fillna(mean_value)

mean_value = df3['iranian_rial_to_usd'].mean()
df3['iranian_rial_to_usd'] = df3['iranian_rial_to_usd'].fillna(mean_value)

mean_value = df3['israeli_new_shekel_to_usd'].mean()
df3['israeli_new_shekel_to_usd'] = df3['israeli_new_shekel_to_usd'].fillna(mean_value)

mean_value = df3['kazakhstani_tenge_to_usd'].mean()
df3['kazakhstani_tenge_to_usd'] = df3['kazakhstani_tenge_to_usd'].fillna(mean_value)

mean_value = df3['korean_won_to_usd'].mean()
df3['korean_won_to_usd'] = df3['korean_won_to_usd'].fillna(mean_value)

mean_value = df3['kuwaiti_dinar_to_usd'].mean()
df3['kuwaiti_dinar_to_usd'] = df3['kuwaiti_dinar_to_usd'].fillna(mean_value)

mean_value = df3['libyan_dinar_to_usd'].mean()
df3['libyan_dinar_to_usd'] = df3['libyan_dinar_to_usd'].fillna(mean_value)

mean_value = df3['malaysian_ringgit_to_usd'].mean()
df3['malaysian_ringgit_to_usd'] = df3['malaysian_ringgit_to_usd'].fillna(mean_value)

mean_value = df3['mauritian_rupee_to_usd'].mean()
df3['mauritian_rupee_to_usd'] = df3['mauritian_rupee_to_usd'].fillna(mean_value)

mean_value = df3['mexican_peso_to_usd'].mean()
df3['mexican_peso_to_usd'] = df3['mexican_peso_to_usd'].fillna(mean_value)

KeyError: 'colombian_peso_to_usd'

In [ ]:
df3.isnull().sum()

In [ ]:
mean_value = df4['Volatility'].mean()
df4['Volatility'] = df4['Volatility'].fillna(mean_value)

In [ ]:
df4.isnull().sum()

In [ ]:
mean_value = df4['Daily_Return'].mean()
df4['Daily_Return'] = df4['Daily_Return'].fillna(mean_value)

In [ ]:
df4.isnull().sum()

In [ ]:
df3

In [ ]:
# Drop rows from index 0 up to 1099
df = df.drop(df.index[:1983]).reset_index(drop=True)

print(f"New number of rows: {len(df)}")

In [ ]:
# Drop rows from index 0 up to 1099
df3 = df3.drop(df3.index[:]67319).reset_index(drop=True)

print(f"New number of rows: {len(df)}")

In [ ]:
df4 = df4.drop(df4.index[:4810]).reset_index(drop=True)

print(f"New number of rows: {len(df)}")

In [ ]:
# Drop rows from index 0 up to 1099
df5 = df5.drop(df5.index[:67319]).reset_index(drop=True)

print(f"New number of rows: {len(df)}")

In [ ]:
df_final = pd.concat([df, df5, df3, df4], ignore_index=True)
df_final

In [ ]:
df_final.sort_values(by=["Asset_Name", "Date"], inplace=True)

In [ ]:
df_final["Daily_Return"] = df_final.groupby("Asset_Name")["Close_Price"].pct_change()

In [ ]:
df_final["Volatility"] = df_final.groupby("Asset_Name")["Daily_Return"].rolling(7).std().reset_index(level=0, drop=True)

In [ ]:
df_final

In [ ]:
df_final12 = pd.concat([df, df5,  df4], ignore_index=True)
df_final12

In [ ]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.preprocessing import LabelEncoder

In [ ]:
df12 = df_final.copy()

In [ ]:
df12.sort_values(by=["Asset_Name", "Date"], inplace=True)

In [ ]:
df12["Daily_Return"] = df12.groupby("Asset_Name")["Close_Price"].pct_change()

In [ ]:
df12["Volatility"] = df12.groupby("Asset_Name")["Daily_Return"]\
                    .rolling(7).std().reset_index(level=0, drop=True)

# Target: Next Day Return
df12["Target_Return"] = df12.groupby("Asset_Name")["Daily_Return"].shift(-1)

In [ ]:
df12.fillna(0, inplace=True)

In [ ]:
le_asset = LabelEncoder()
le_type = LabelEncoder()
le_sector = LabelEncoder()

df12["Asset_Name_Enc"] = le_asset.fit_transform(df12["Asset_Name"])
df12["Asset_Type_Enc"] = le_type.fit_transform(df12["Asset_Type"])
df12["Sector_Enc"] = le_sector.fit_transform(df12["Sector"])

In [ ]:
X = df12[[
    "Close_Price",
    "Daily_Return",
    "Volatility",
    "Asset_Name_Enc",
    "Asset_Type_Enc",
    "Sector_Enc"
]]

y = df12["Target_Return"]

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)

In [ ]:
model = RandomForestRegressor(n_estimators=100, random_state=42)

model.fit(X_train, y_train)

In [ ]:
y_pred = model.predict(X_test)

In [ ]:
rmse = np.sqrt(mean_squared_error(y_test, y_pred))

In [ ]:
r2 = r2_score(y_test, y_pred)

print("RMSE:", rmse)
print("R2 Score:", r2)

In [ ]:
# ==========================================
# AI Investment Model (Improved Version)
# ==========================================

import pandas as pd
import numpy as np

from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.model_selection import train_test_split
from xgboost import XGBRegressor

# ==========================================
# 1. LOAD DATA
# ==========================================

df = df_final.copy()   # your cleaned dataset

# Fix duplicate date column if exists
if "date" in df.columns:
    df.drop(columns=["date"], inplace=True)

# Convert Date
df["Date"] = pd.to_datetime(df["Date"])

# Sort properly (VERY IMPORTANT)
df.sort_values(by=["Asset_Name", "Date"], inplace=True)

# ==========================================
# 2. FEATURE ENGINEERING (ADVANCED)
# ==========================================

# Moving Averages
df["MA_7"] = df.groupby("Asset_Name")["Close_Price"].rolling(7).mean().reset_index(0, drop=True)
df["MA_21"] = df.groupby("Asset_Name")["Close_Price"].rolling(21).mean().reset_index(0, drop=True)

# Price Range (intraday volatility)
df["Price_Range"] = df["High_Price"] - df["Low_Price"]

# Momentum
df["Momentum_5"] = df["Close_Price"] - df.groupby("Asset_Name")["Close_Price"].shift(5)

# Lag Features
df["Lag_1"] = df.groupby("Asset_Name")["Daily_Return"].shift(1)
df["Lag_2"] = df.groupby("Asset_Name")["Daily_Return"].shift(2)
df["Lag_3"] = df.groupby("Asset_Name")["Daily_Return"].shift(3)

# Rolling Returns
df["Return_7"] = df.groupby("Asset_Name")["Close_Price"].pct_change(7)
df["Return_21"] = df.groupby("Asset_Name")["Close_Price"].pct_change(21)

# Sharpe Ratio
df["Sharpe_Ratio"] = df["Daily_Return"] / (df["Volatility"] + 1e-6)

# TARGET: Future Return (Next Day)
df["Target"] = df.groupby("Asset_Name")["Daily_Return"].shift(-1)

# ==========================================
# 3. CLEAN DATA
# ==========================================

df.replace([np.inf, -np.inf], 0, inplace=True)
df.fillna(0, inplace=True)

# ==========================================
# 4. ENCODE CATEGORICAL DATA
# ==========================================

le_asset = LabelEncoder()
le_type = LabelEncoder()
le_sector = LabelEncoder()

df["Asset_Name_Enc"] = le_asset.fit_transform(df["Asset_Name"])
df["Asset_Type_Enc"] = le_type.fit_transform(df["Asset_Type"])
df["Sector_Enc"] = le_sector.fit_transform(df["Sector"])

# ==========================================
# 5. SELECT FEATURES
# ==========================================

features = [
    "Open_Price", "High_Price", "Low_Price", "Close_Price",
    "Volume", "Daily_Return", "Volatility",
    "MA_7", "MA_21",
    "Price_Range", "Momentum_5",
    "Lag_1", "Lag_2", "Lag_3",
    "Return_7", "Return_21",
    "Sharpe_Ratio",
    "Asset_Name_Enc", "Asset_Type_Enc", "Sector_Enc"
]

X = df[features]
y = df["Target"]

# ==========================================
# 6. TRAIN-TEST SPLIT (Time-Aware)
# ==========================================

split_index = int(len(df) * 0.8)

X_train, X_test = X.iloc[:split_index], X.iloc[split_index:]
y_train, y_test = y.iloc[:split_index], y.iloc[split_index:]

# ==========================================
# 7. MODEL (XGBoost Advanced)
# ==========================================

model = XGBRegressor(
    n_estimators=400,
    max_depth=6,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8
)

model.fit(X_train, y_train)

# ==========================================
# 8. EVALUATION
# ==========================================

y_pred = model.predict(X_test)

rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

print("RMSE:", rmse)
print("R2 Score:", r2)

# ==========================================
# 9. PREDICTIONS
# ==========================================

df["Predicted_Return"] = model.predict(X)

# ==========================================
# 10. BUILD RECOMMENDATION ENGINE
# ==========================================

asset_summary = df.groupby("Asset_Name").agg({
    "Predicted_Return": "mean",
    "Volatility": "mean"
}).reset_index()

# Risk classification
def risk_level(vol):
    if vol < 0.01:
        return "Low"
    elif vol < 0.03:
        return "Medium"
    else:
        return "High"

asset_summary["Risk_Level"] = asset_summary["Volatility"].apply(risk_level)

# ==========================================
# 11. RECOMMEND FUNCTION
# ==========================================

def recommend(amount, risk):

    filtered = asset_summary[asset_summary["Risk_Level"] == risk]

    filtered = filtered.sort_values(by="Predicted_Return", ascending=False)

    total = filtered["Predicted_Return"].sum()

    filtered["Weight"] = filtered["Predicted_Return"] / total
    filtered["Investment"] = filtered["Weight"] * amount

    return filtered[["Asset_Name", "Investment", "Predicted_Return"]]

# ==========================================
# 12. TEST
# ==========================================

result = recommend(200, "Medium")

print("\nRecommended Portfolio:\n")
print(result)