In [136]:
import pandas as pd
import numpy as np

In [137]:
df =pd.read_csv("BTC-USD.csv")
df

,Date,Open,High,Low,Close,Adj Close,Volume
0,2014-09-17,465.864014,468.174011,452.421997,457.334015,457.334015,21056800
1,2014-09-18,456.859985,456.859985,413.104004,424.440002,424.440002,34483200
2,2014-09-19,424.102997,427.834991,384.532013,394.795990,394.795990,37919700
3,2014-09-20,394.673004,423.295990,389.882996,408.903992,408.903992,36863600
4,2014-09-21,408.084991,412.425995,393.181000,398.821014,398.821014,26580100
...,...,...,...,...,...,...,...
2708,2022-02-15,42586.464844,44667.218750,42491.035156,44575.203125,44575.203125,22721659051
2709,2022-02-16,44578.277344,44578.277344,43456.691406,43961.859375,43961.859375,19792547657
2710,2022-02-17,43937.070313,44132.972656,40249.371094,40538.011719,40538.011719,26246662813
2711,2022-02-18,40552.132813,40929.152344,39637.617188,40030.976563,40030.976563,23310007704
2712,2022-02-19,40022.132813,40246.027344,40010.867188,40126.429688,40126.429688,22263900160

In [138]:
df4=pd.read_csv("gold_prices_10y.csv")
df4

,Date,Close,High,Low,Open,Volume,Adj Close,Daily_Return,MA_20,MA_50,MA_200,Volatility_20,Year,Month,Day_of_Week,Quarter
0,29-01-2016,106.949997,107.000000,106.260002,106.610001,8098700,106.949997,NaN,NaN,NaN,NaN,NaN,2016,1,4,1
1,01-02-2016,108.050003,108.150002,107.529999,107.540001,10471800,108.050003,1.028524,NaN,NaN,NaN,NaN,2016,2,0,1
2,02-02-2016,108.089996,108.180000,107.349998,107.919998,6656000,108.089996,0.037014,NaN,NaN,NaN,NaN,2016,2,1,1
3,03-02-2016,109.250000,109.580002,107.900002,107.910004,15785200,109.250000,1.073183,NaN,NaN,NaN,NaN,2016,2,2,1
4,04-02-2016,110.570000,110.699997,109.919998,110.449997,13213700,110.570000,1.208238,NaN,NaN,NaN,NaN,2016,2,3,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2506,16-01-2026,421.290008,424.799988,417.040008,422.799988,20951600,421.290008,-0.481888,410.588002,393.921000,339.46595,1.482148,2026,1,4,1
2507,20-01-2026,437.230011,438.140015,434.100006,436.690002,21308100,437.230011,3.783617,412.521002,395.335400,340.21130,1.670545,2026,1,1,1
2508,21-01-2026,443.600006,448.000000,437.109985,446.869995,38830200,443.600006,1.456898,414.750003,396.886000,340.99720,1.682109,2026,1,2,1
2509,22-01-2026,451.790008,452.980011,443.559998,443.839996,19251200,451.790008,1.846258,416.928003,398.555601,341.85755,1.659640,2026,1,3,1
2510,23-01-2026,458.000000,458.750000,453.450012,454.109985,21497000,458.000000,1.374530,419.146002,400.148001,342.77900,1.660933,2026,1,4,1

In [139]:
df5=pd.read_csv("NIFTY 100_15minute.csv")

In [140]:
df5

                      date      open      high       low     close  volume
0      2015-01-09 09:15:00   8300.60   8317.25   8300.60   8307.50       0
1      2015-01-09 09:30:00   8307.50   8308.55   8290.90   8297.00       0
2      2015-01-09 09:45:00   8298.30   8298.85   8288.25   8296.05       0
3      2015-01-09 10:00:00   8296.05   8300.65   8288.45   8294.75       0
4      2015-01-09 10:15:00   8294.75   8304.50   8292.00   8304.00       0
...                    ...       ...       ...       ...       ...     ...
68044  2026-01-22 16:45:00  25860.25  25860.25  25860.25  25860.25       0
68045  2026-01-22 17:00:00  25860.25  25860.25  25860.25  25860.25       0
68046  2026-01-22 17:15:00  25860.25  25860.25  25860.25  25860.25       0
68047  2026-01-22 17:30:00  25860.25  25860.25  25860.25  25860.25       0
68048  2026-01-22 17:45:00  25860.25  25860.25  25860.25  25860.25       0

[68049 rows x 6 columns]

In [141]:
df5.rename(columns={"date": "Date"}, inplace=True)

In [142]:
df5["Date"] = pd.to_datetime(df5["Date"])
df5["Date"] = df5["Date"].dt.normalize()

In [143]:
df5

            Date      open      high       low     close  volume
0     2015-01-09   8300.60   8317.25   8300.60   8307.50       0
1     2015-01-09   8307.50   8308.55   8290.90   8297.00       0
2     2015-01-09   8298.30   8298.85   8288.25   8296.05       0
3     2015-01-09   8296.05   8300.65   8288.45   8294.75       0
4     2015-01-09   8294.75   8304.50   8292.00   8304.00       0
...          ...       ...       ...       ...       ...     ...
68044 2026-01-22  25860.25  25860.25  25860.25  25860.25       0
68045 2026-01-22  25860.25  25860.25  25860.25  25860.25       0
68046 2026-01-22  25860.25  25860.25  25860.25  25860.25       0
68047 2026-01-22  25860.25  25860.25  25860.25  25860.25       0
68048 2026-01-22  25860.25  25860.25  25860.25  25860.25       0

[68049 rows x 6 columns]

In [144]:
df = df.drop('Adj Close', axis=1)
df

,Date,Open,High,Low,Close,Volume
0,2014-09-17,465.864014,468.174011,452.421997,457.334015,21056800
1,2014-09-18,456.859985,456.859985,413.104004,424.440002,34483200
2,2014-09-19,424.102997,427.834991,384.532013,394.795990,37919700
3,2014-09-20,394.673004,423.295990,389.882996,408.903992,36863600
4,2014-09-21,408.084991,412.425995,393.181000,398.821014,26580100
...,...,...,...,...,...,...
2708,2022-02-15,42586.464844,44667.218750,42491.035156,44575.203125,22721659051
2709,2022-02-16,44578.277344,44578.277344,43456.691406,43961.859375,19792547657
2710,2022-02-17,43937.070313,44132.972656,40249.371094,40538.011719,26246662813
2711,2022-02-18,40552.132813,40929.152344,39637.617188,40030.976563,23310007704
2712,2022-02-19,40022.132813,40246.027344,40010.867188,40126.429688,22263900160

In [145]:
df = df.rename(columns={
    'Open': 'Open_Price',
    'High': 'High_Price',
    'Low': 'Low_Price',
    'Close': 'Close_Price'
})

In [146]:
df["Asset_Name"] = "Bitcoin"
df["Asset_Type"] = "Crypto"
df["Sector"] = "Cryptocurrency"
df

,Date,Open_Price,High_Price,Low_Price,Close_Price,Volume,Asset_Name,Asset_Type,Sector
0,2014-09-17,465.864014,468.174011,452.421997,457.334015,21056800,Bitcoin,Crypto,Cryptocurrency
1,2014-09-18,456.859985,456.859985,413.104004,424.440002,34483200,Bitcoin,Crypto,Cryptocurrency
2,2014-09-19,424.102997,427.834991,384.532013,394.795990,37919700,Bitcoin,Crypto,Cryptocurrency
3,2014-09-20,394.673004,423.295990,389.882996,408.903992,36863600,Bitcoin,Crypto,Cryptocurrency
4,2014-09-21,408.084991,412.425995,393.181000,398.821014,26580100,Bitcoin,Crypto,Cryptocurrency
...,...,...,...,...,...,...,...,...,...
2708,2022-02-15,42586.464844,44667.218750,42491.035156,44575.203125,22721659051,Bitcoin,Crypto,Cryptocurrency
2709,2022-02-16,44578.277344,44578.277344,43456.691406,43961.859375,19792547657,Bitcoin,Crypto,Cryptocurrency
2710,2022-02-17,43937.070313,44132.972656,40249.371094,40538.011719,26246662813,Bitcoin,Crypto,Cryptocurrency
2711,2022-02-18,40552.132813,40929.152344,39637.617188,40030.976563,23310007704,Bitcoin,Crypto,Cryptocurrency
2712,2022-02-19,40022.132813,40246.027344,40010.867188,40126.429688,22263900160,Bitcoin,Crypto,Cryptocurrency

In [147]:
cols_to_drop1 = [
    "Adj Close","MA_20",	"MA_50",	"MA_200","Year","Month","Day_of_Week",	"Quarter"
]

# Dropping the columns
df4 = df4.drop(columns=cols_to_drop1)

# Checking the new shape to confirm they are gone
print(f"New shape: {df4.shape}")
df4.head()

New shape: (2511, 8)

,Date,Close,High,Low,Open,Volume,Daily_Return,Volatility_20
0,29-01-2016,106.949997,107.000000,106.260002,106.610001,8098700,NaN,NaN
1,01-02-2016,108.050003,108.150002,107.529999,107.540001,10471800,1.028524,NaN
2,02-02-2016,108.089996,108.180000,107.349998,107.919998,6656000,0.037014,NaN
3,03-02-2016,109.250000,109.580002,107.900002,107.910004,15785200,1.073183,NaN
4,04-02-2016,110.570000,110.699997,109.919998,110.449997,13213700,1.208238,NaN

In [148]:
df4.rename(columns={
    "Open": "Open_Price",
    "High": "High_Price",
    "Low": "Low_Price",
    "Close": "Close_Price",
    "Volatility_20": "Volatility"
}, inplace=True)

In [149]:
df4["Asset_Name"] = "Gold"
df4["Asset_Type"] = "Commodity"
df4["Sector"] = "Precious Metal"

In [150]:
df5.rename(columns={
    "open": "Open_Price",
    "high": "High_Price",
    "low": "Low_Price",
    "close": "Close_Price",
    "volume": "Volume"
}, inplace=True)

df5["Asset_Name"] = "BankNifty"   
df5["Asset_Type"] = "Index"            
df5["Sector"] = "Market Index"

In [151]:
mean_value = df4['Volatility'].mean()
df4['Volatility'] = df4['Volatility'].fillna(mean_value)

In [152]:
df4

,Date,Close_Price,High_Price,Low_Price,Open_Price,Volume,Daily_Return,Volatility,Asset_Name,Asset_Type,Sector
0,29-01-2016,106.949997,107.000000,106.260002,106.610001,8098700,NaN,0.871612,Gold,Commodity,Precious Metal
1,01-02-2016,108.050003,108.150002,107.529999,107.540001,10471800,1.028524,0.871612,Gold,Commodity,Precious Metal
2,02-02-2016,108.089996,108.180000,107.349998,107.919998,6656000,0.037014,0.871612,Gold,Commodity,Precious Metal
3,03-02-2016,109.250000,109.580002,107.900002,107.910004,15785200,1.073183,0.871612,Gold,Commodity,Precious Metal
4,04-02-2016,110.570000,110.699997,109.919998,110.449997,13213700,1.208238,0.871612,Gold,Commodity,Precious Metal
...,...,...,...,...,...,...,...,...,...,...,...
2506,16-01-2026,421.290008,424.799988,417.040008,422.799988,20951600,-0.481888,1.482148,Gold,Commodity,Precious Metal
2507,20-01-2026,437.230011,438.140015,434.100006,436.690002,21308100,3.783617,1.670545,Gold,Commodity,Precious Metal
2508,21-01-2026,443.600006,448.000000,437.109985,446.869995,38830200,1.456898,1.682109,Gold,Commodity,Precious Metal
2509,22-01-2026,451.790008,452.980011,443.559998,443.839996,19251200,1.846258,1.659640,Gold,Commodity,Precious Metal
2510,23-01-2026,458.000000,458.750000,453.450012,454.109985,21497000,1.374530,1.660933,Gold,Commodity,Precious Metal

In [153]:
df4.isnull().sum()

Date            0
Close_Price     0
High_Price      0
Low_Price       0
Open_Price      0
Volume          0
Daily_Return    1
Volatility      0
Asset_Name      0
Asset_Type      0
Sector          0
dtype: int64

In [154]:
df5

,Date,Open_Price,High_Price,Low_Price,Close_Price,Volume,Asset_Name,Asset_Type,Sector
0,2015-01-09,8300.60,8317.25,8300.60,8307.50,0,BankNifty,Index,Market Index
1,2015-01-09,8307.50,8308.55,8290.90,8297.00,0,BankNifty,Index,Market Index
2,2015-01-09,8298.30,8298.85,8288.25,8296.05,0,BankNifty,Index,Market Index
3,2015-01-09,8296.05,8300.65,8288.45,8294.75,0,BankNifty,Index,Market Index
4,2015-01-09,8294.75,8304.50,8292.00,8304.00,0,BankNifty,Index,Market Index
...,...,...,...,...,...,...,...,...,...
68044,2026-01-22,25860.25,25860.25,25860.25,25860.25,0,BankNifty,Index,Market Index
68045,2026-01-22,25860.25,25860.25,25860.25,25860.25,0,BankNifty,Index,Market Index
68046,2026-01-22,25860.25,25860.25,25860.25,25860.25,0,BankNifty,Index,Market Index
68047,2026-01-22,25860.25,25860.25,25860.25,25860.25,0,BankNifty,Index,Market Index
68048,2026-01-22,25860.25,25860.25,25860.25,25860.25,0,BankNifty,Index,Market Index

In [155]:
df = df.drop(df.index[:1983]).reset_index(drop=True)

print(f"New number of rows: {len(df)}")

New number of rows: 730

In [156]:
df5 = df5.drop(df5.index[:67319]).reset_index(drop=True)

print(f"New number of rows: {len(df)}")

New number of rows: 730

In [157]:
df5

,Date,Open_Price,High_Price,Low_Price,Close_Price,Volume,Asset_Name,Asset_Type,Sector
0,2025-12-11,26315.95,26345.55,26309.15,26333.60,0,BankNifty,Index,Market Index
1,2025-12-11,26334.25,26351.30,26300.95,26300.95,0,BankNifty,Index,Market Index
2,2025-12-11,26301.25,26310.70,26271.35,26304.45,0,BankNifty,Index,Market Index
3,2025-12-11,26304.55,26338.15,26298.00,26329.25,0,BankNifty,Index,Market Index
4,2025-12-11,26329.35,26344.25,26320.10,26340.75,0,BankNifty,Index,Market Index
...,...,...,...,...,...,...,...,...,...
725,2026-01-22,25860.25,25860.25,25860.25,25860.25,0,BankNifty,Index,Market Index
726,2026-01-22,25860.25,25860.25,25860.25,25860.25,0,BankNifty,Index,Market Index
727,2026-01-22,25860.25,25860.25,25860.25,25860.25,0,BankNifty,Index,Market Index
728,2026-01-22,25860.25,25860.25,25860.25,25860.25,0,BankNifty,Index,Market Index
729,2026-01-22,25860.25,25860.25,25860.25,25860.25,0,BankNifty,Index,Market Index

In [158]:
df4 = df4.drop(df4.index[:1781]).reset_index(drop=True)

print(f"New number of rows: {len(df)}")
df4

New number of rows: 730

,Date,Close_Price,High_Price,Low_Price,Open_Price,Volume,Daily_Return,Volatility,Asset_Name,Asset_Type,Sector
0,27-02-2023,169.009995,169.229996,168.550003,168.880005,4509200,0.392033,0.855431,Gold,Commodity,Precious Metal
1,28-02-2023,169.779999,170.250000,168.589996,168.779999,6761600,0.455597,0.871538,Gold,Commodity,Precious Metal
2,01-03-2023,170.759995,171.490005,170.470001,170.949997,6590500,0.577215,0.880761,Gold,Commodity,Precious Metal
3,02-03-2023,170.660004,170.979996,170.360001,170.520004,3950700,-0.058556,0.808767,Gold,Commodity,Precious Metal
4,03-03-2023,172.490005,172.600006,170.979996,171.449997,6894500,1.072309,0.751174,Gold,Commodity,Precious Metal
...,...,...,...,...,...,...,...,...,...,...,...
725,16-01-2026,421.290008,424.799988,417.040008,422.799988,20951600,-0.481888,1.482148,Gold,Commodity,Precious Metal
726,20-01-2026,437.230011,438.140015,434.100006,436.690002,21308100,3.783617,1.670545,Gold,Commodity,Precious Metal
727,21-01-2026,443.600006,448.000000,437.109985,446.869995,38830200,1.456898,1.682109,Gold,Commodity,Precious Metal
728,22-01-2026,451.790008,452.980011,443.559998,443.839996,19251200,1.846258,1.659640,Gold,Commodity,Precious Metal
729,23-01-2026,458.000000,458.750000,453.450012,454.109985,21497000,1.374530,1.660933,Gold,Commodity,Precious Metal

In [159]:
df5.sample(2)

,Date,Open_Price,High_Price,Low_Price,Close_Price,Volume,Asset_Name,Asset_Type,Sector
404,2026-01-05,26925.15,26940.45,26914.25,26938.45,0,BankNifty,Index,Market Index
42,2025-12-12,26538.25,26545.75,26527.95,26542.70,0,BankNifty,Index,Market Index

In [160]:
df5['Date'] = pd.to_datetime(df5['Date'])
df['Date'] = pd.to_datetime(df['Date'])
df4['Date'] = pd.to_datetime(df4['Date'])

C:\Users\Raj Upadhyay\AppData\Local\Temp\ipykernel_17752\106444123.py:3: UserWarning: Parsing dates in DD/MM/YYYY format when dayfirst=False (the default) was specified. This may lead to inconsistently parsed dates! Specify a format to ensure consistent parsing.
  df4['Date'] = pd.to_datetime(df4['Date'])

In [161]:
df.sample(2)

,Date,Open_Price,High_Price,Low_Price,Close_Price,Volume,Asset_Name,Asset_Type,Sector
150,2020-07-20,9187.220703,9214.270508,9137.509766,9164.231445,13755604146,Bitcoin,Crypto,Cryptocurrency
183,2020-08-22,11585.477539,11689.407227,11448.805664,11681.825195,20224191306,Bitcoin,Crypto,Cryptocurrency

In [162]:
df4.sample(2)

,Date,Close_Price,High_Price,Low_Price,Open_Price,Volume,Daily_Return,Volatility,Asset_Name,Asset_Type,Sector
92,2023-11-07,179.449997,179.710007,179.130005,179.429993,2818800,0.374761,0.503119,Gold,Commodity,Precious Metal
433,2024-11-14,237.009995,237.990005,236.130005,236.570007,8262400,-0.260914,1.193068,Gold,Commodity,Precious Metal

In [163]:
df4.sample(2)

,Date,Close_Price,High_Price,Low_Price,Open_Price,Volume,Daily_Return,Volatility,Asset_Name,Asset_Type,Sector
311,2024-05-22,220.110001,223.240005,219.740005,223.089996,8903100,-1.837397,1.017268,Gold,Commodity,Precious Metal
533,2025-11-04,297.929993,299.269989,296.809998,297.959992,21080100,1.908666,1.416385,Gold,Commodity,Precious Metal

In [164]:
df4["Profit"] = df4["Close_Price"] - df4["Open_Price"]

df4["Daily_Return"] = df4["Profit"] / df4["Open_Price"]

In [165]:
df4.sample(2)

,Date,Close_Price,High_Price,Low_Price,Open_Price,Volume,Daily_Return,Volatility,Asset_Name,Asset_Type,Sector,Profit
173,2023-02-11,184.119995,184.279999,183.500000,184.130005,7343700,-0.000054,0.952210,Gold,Commodity,Precious Metal,-0.010010
586,2025-06-30,304.829987,304.920013,301.950012,302.390015,8192100,0.008069,1.119192,Gold,Commodity,Precious Metal,2.439972

In [166]:
df5["Profit"] = df5["Close_Price"] - df5["Open_Price"]

df5["Daily_Return"] = df5["Profit"] / df5["Open_Price"]

In [167]:
df5.sample(2)

,Date,Open_Price,High_Price,Low_Price,Close_Price,Volume,Asset_Name,Asset_Type,Sector,Profit,Daily_Return
207,2025-12-23,26726.8,26729.45,26716.3,26716.30,0,BankNifty,Index,Market Index,-10.50,-0.000393
666,2026-01-20,25930.2,25936.05,25889.6,25900.45,0,BankNifty,Index,Market Index,-29.75,-0.001147

In [168]:
df_final=pd.concat([df5,df,df4],ignore_index=True)
df_final

,Date,Open_Price,High_Price,Low_Price,Close_Price,Volume,Asset_Name,Asset_Type,Sector,Profit,Daily_Return,Volatility
0,2025-12-11,26315.950000,26345.550000,26309.150000,26333.600000,0,BankNifty,Index,Market Index,17.650000,0.000671,NaN
1,2025-12-11,26334.250000,26351.300000,26300.950000,26300.950000,0,BankNifty,Index,Market Index,-33.300000,-0.001265,NaN
2,2025-12-11,26301.250000,26310.700000,26271.350000,26304.450000,0,BankNifty,Index,Market Index,3.200000,0.000122,NaN
3,2025-12-11,26304.550000,26338.150000,26298.000000,26329.250000,0,BankNifty,Index,Market Index,24.700000,0.000939,NaN
4,2025-12-11,26329.350000,26344.250000,26320.100000,26340.750000,0,BankNifty,Index,Market Index,11.400000,0.000433,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
2185,2026-01-16,422.799988,424.799988,417.040008,421.290008,20951600,Gold,Commodity,Precious Metal,-1.509979,-0.003571,1.482148
2186,2026-01-20,436.690002,438.140015,434.100006,437.230011,21308100,Gold,Commodity,Precious Metal,0.540009,0.001237,1.670545
2187,2026-01-21,446.869995,448.000000,437.109985,443.600006,38830200,Gold,Commodity,Precious Metal,-3.269989,-0.007318,1.682109
2188,2026-01-22,443.839996,452.980011,443.559998,451.790008,19251200,Gold,Commodity,Precious Metal,7.950012,0.017912,1.659640
2189,2026-01-23,454.109985,458.750000,453.450012,458.000000,21497000,Gold,Commodity,Precious Metal,3.890015,0.008566,1.660933

In [169]:
df_final

,Date,Open_Price,High_Price,Low_Price,Close_Price,Volume,Asset_Name,Asset_Type,Sector,Profit,Daily_Return,Volatility
0,2025-12-11,26315.950000,26345.550000,26309.150000,26333.600000,0,BankNifty,Index,Market Index,17.650000,0.000671,NaN
1,2025-12-11,26334.250000,26351.300000,26300.950000,26300.950000,0,BankNifty,Index,Market Index,-33.300000,-0.001265,NaN
2,2025-12-11,26301.250000,26310.700000,26271.350000,26304.450000,0,BankNifty,Index,Market Index,3.200000,0.000122,NaN
3,2025-12-11,26304.550000,26338.150000,26298.000000,26329.250000,0,BankNifty,Index,Market Index,24.700000,0.000939,NaN
4,2025-12-11,26329.350000,26344.250000,26320.100000,26340.750000,0,BankNifty,Index,Market Index,11.400000,0.000433,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
2185,2026-01-16,422.799988,424.799988,417.040008,421.290008,20951600,Gold,Commodity,Precious Metal,-1.509979,-0.003571,1.482148
2186,2026-01-20,436.690002,438.140015,434.100006,437.230011,21308100,Gold,Commodity,Precious Metal,0.540009,0.001237,1.670545
2187,2026-01-21,446.869995,448.000000,437.109985,443.600006,38830200,Gold,Commodity,Precious Metal,-3.269989,-0.007318,1.682109
2188,2026-01-22,443.839996,452.980011,443.559998,451.790008,19251200,Gold,Commodity,Precious Metal,7.950012,0.017912,1.659640
2189,2026-01-23,454.109985,458.750000,453.450012,458.000000,21497000,Gold,Commodity,Precious Metal,3.890015,0.008566,1.660933

In [170]:
df_final.isnull().sum()

Date               0
Open_Price         0
High_Price         0
Low_Price          0
Close_Price        0
Volume             0
Asset_Name         0
Asset_Type         0
Sector             0
Profit           730
Daily_Return     730
Volatility      1460
dtype: int64

In [171]:
df_final.drop('Volatility', axis=1, inplace=True)

In [172]:
df_final

,Date,Open_Price,High_Price,Low_Price,Close_Price,Volume,Asset_Name,Asset_Type,Sector,Profit,Daily_Return
0,2025-12-11,26315.950000,26345.550000,26309.150000,26333.600000,0,BankNifty,Index,Market Index,17.650000,0.000671
1,2025-12-11,26334.250000,26351.300000,26300.950000,26300.950000,0,BankNifty,Index,Market Index,-33.300000,-0.001265
2,2025-12-11,26301.250000,26310.700000,26271.350000,26304.450000,0,BankNifty,Index,Market Index,3.200000,0.000122
3,2025-12-11,26304.550000,26338.150000,26298.000000,26329.250000,0,BankNifty,Index,Market Index,24.700000,0.000939
4,2025-12-11,26329.350000,26344.250000,26320.100000,26340.750000,0,BankNifty,Index,Market Index,11.400000,0.000433
...,...,...,...,...,...,...,...,...,...,...,...
2185,2026-01-16,422.799988,424.799988,417.040008,421.290008,20951600,Gold,Commodity,Precious Metal,-1.509979,-0.003571
2186,2026-01-20,436.690002,438.140015,434.100006,437.230011,21308100,Gold,Commodity,Precious Metal,0.540009,0.001237
2187,2026-01-21,446.869995,448.000000,437.109985,443.600006,38830200,Gold,Commodity,Precious Metal,-3.269989,-0.007318
2188,2026-01-22,443.839996,452.980011,443.559998,451.790008,19251200,Gold,Commodity,Precious Metal,7.950012,0.017912
2189,2026-01-23,454.109985,458.750000,453.450012,458.000000,21497000,Gold,Commodity,Precious Metal,3.890015,0.008566

Date              0
Open_Price        0
High_Price        0
Low_Price         0
Close_Price       0
Volume            0
Asset_Name        0
Asset_Type        0
Sector            0
Profit          730
Daily_Return    730
dtype: int64

In [177]:
print(df["Asset_Type"].value_counts())

Crypto    730
Name: Asset_Type, dtype: int64

In [178]:
print(df["Asset_Type"].value_counts())

Crypto    730
Name: Asset_Type, dtype: int64

In [179]:
print(df["Asset_Type"].value_counts())

Crypto    730
Name: Asset_Type, dtype: int64

In [180]:
df_final["Asset_Type"].value_counts()

Index        730
Crypto       730
Commodity    730
Name: Asset_Type, dtype: int64

In [200]:
df_final.sample(2)
df_final.isnull().sum()

Date              0
Open_Price        0
High_Price        0
Low_Price         0
Close_Price       0
Volume            0
Asset_Name        0
Asset_Type        0
Sector            0
Profit          730
Daily_Return    730
dtype: int64

In [212]:
print(model.n_features_in_)

11

In [214]:
print(list(X.columns))

['Open_Price', 'High_Price', 'Low_Price', 'Close_Price', 'Volume', 'Asset_Name', 'Asset_Type', 'Sector', 'Year', 'Month', 'Day']

In [215]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier

# 1. Setup Data (Only your 4 features)
features = ["Open_Price", "High_Price", "Low_Price", "Volume"]
X_raw = df_final[features].copy()
y_raw = df_final["Asset_Type"].copy()

# 2. Transform to % Change (Crucial for realistic 0.80 accuracy)
X = X_raw.pct_change().replace([np.inf, -np.inf], np.nan).dropna()
y = y_raw.iloc[X.index] # Keep y aligned with X after dropping NaNs

# 3. Encode Target
le = LabelEncoder()
y_encoded = le.fit_transform(y)

# 4. Split
X_train, X_test, y_train, y_test = train_test_split(
    X, y_encoded, test_size=0.2, random_state=42, stratify=y_encoded
)

# 5. Train Model
model = RandomForestClassifier(n_estimators=100, max_depth=5, random_state=42)
model.fit(X_train, y_train)

# 6. Results
acc = model.score(X_test, y_test)
print(f"Realistic Accuracy: {acc:.4f}")

# -----------------------------
# 7. QUICK TESTER (Single Input)
# -----------------------------
def predict_now(open_p, high_p, low_p, vol):
    # This simulates a small % change for a single prediction
    test_data = np.array([[(high_p-open_p)/open_p, (high_p-low_p)/low_p, (low_p-open_p)/open_p, 0.02]])
    pred = model.predict(test_data)[0]
    return le.inverse_transform([pred])[0]

# Example test
print("Prediction Test:", predict_now(50000, 51000, 49500, 100000))

Realistic Accuracy: 0.8390
Prediction Test: Crypto

C:\Users\Raj Upadhyay\.vscode\cli\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(