In [1]:
import pandas as pd
import numpy as np

In [2]:
df =pd.read_csv("BTC-USD.csv")
df

,Date,Open,High,Low,Close,Adj Close,Volume
0,2014-09-17,465.864014,468.174011,452.421997,457.334015,457.334015,21056800
1,2014-09-18,456.859985,456.859985,413.104004,424.440002,424.440002,34483200
2,2014-09-19,424.102997,427.834991,384.532013,394.795990,394.795990,37919700
3,2014-09-20,394.673004,423.295990,389.882996,408.903992,408.903992,36863600
4,2014-09-21,408.084991,412.425995,393.181000,398.821014,398.821014,26580100
...,...,...,...,...,...,...,...
2708,2022-02-15,42586.464844,44667.218750,42491.035156,44575.203125,44575.203125,22721659051
2709,2022-02-16,44578.277344,44578.277344,43456.691406,43961.859375,43961.859375,19792547657
2710,2022-02-17,43937.070313,44132.972656,40249.371094,40538.011719,40538.011719,26246662813
2711,2022-02-18,40552.132813,40929.152344,39637.617188,40030.976563,40030.976563,23310007704
2712,2022-02-19,40022.132813,40246.027344,40010.867188,40126.429688,40126.429688,22263900160

In [3]:
df4=pd.read_csv("gold_prices_10y.csv")
df4

,Date,Close,High,Low,Open,Volume,Adj Close,Daily_Return,MA_20,MA_50,MA_200,Volatility_20,Year,Month,Day_of_Week,Quarter
0,29-01-2016,106.949997,107.000000,106.260002,106.610001,8098700,106.949997,NaN,NaN,NaN,NaN,NaN,2016,1,4,1
1,01-02-2016,108.050003,108.150002,107.529999,107.540001,10471800,108.050003,1.028524,NaN,NaN,NaN,NaN,2016,2,0,1
2,02-02-2016,108.089996,108.180000,107.349998,107.919998,6656000,108.089996,0.037014,NaN,NaN,NaN,NaN,2016,2,1,1
3,03-02-2016,109.250000,109.580002,107.900002,107.910004,15785200,109.250000,1.073183,NaN,NaN,NaN,NaN,2016,2,2,1
4,04-02-2016,110.570000,110.699997,109.919998,110.449997,13213700,110.570000,1.208238,NaN,NaN,NaN,NaN,2016,2,3,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2506,16-01-2026,421.290008,424.799988,417.040008,422.799988,20951600,421.290008,-0.481888,410.588002,393.921000,339.46595,1.482148,2026,1,4,1
2507,20-01-2026,437.230011,438.140015,434.100006,436.690002,21308100,437.230011,3.783617,412.521002,395.335400,340.21130,1.670545,2026,1,1,1
2508,21-01-2026,443.600006,448.000000,437.109985,446.869995,38830200,443.600006,1.456898,414.750003,396.886000,340.99720,1.682109,2026,1,2,1
2509,22-01-2026,451.790008,452.980011,443.559998,443.839996,19251200,451.790008,1.846258,416.928003,398.555601,341.85755,1.659640,2026,1,3,1
2510,23-01-2026,458.000000,458.750000,453.450012,454.109985,21497000,458.000000,1.374530,419.146002,400.148001,342.77900,1.660933,2026,1,4,1

In [4]:
df5=pd.read_csv("NIFTY 100_15minute.csv")

In [5]:
df5

                      date      open      high       low     close  volume
0      2015-01-09 09:15:00   8300.60   8317.25   8300.60   8307.50       0
1      2015-01-09 09:30:00   8307.50   8308.55   8290.90   8297.00       0
2      2015-01-09 09:45:00   8298.30   8298.85   8288.25   8296.05       0
3      2015-01-09 10:00:00   8296.05   8300.65   8288.45   8294.75       0
4      2015-01-09 10:15:00   8294.75   8304.50   8292.00   8304.00       0
...                    ...       ...       ...       ...       ...     ...
68044  2026-01-22 16:45:00  25860.25  25860.25  25860.25  25860.25       0
68045  2026-01-22 17:00:00  25860.25  25860.25  25860.25  25860.25       0
68046  2026-01-22 17:15:00  25860.25  25860.25  25860.25  25860.25       0
68047  2026-01-22 17:30:00  25860.25  25860.25  25860.25  25860.25       0
68048  2026-01-22 17:45:00  25860.25  25860.25  25860.25  25860.25       0

[68049 rows x 6 columns]

In [6]:
df5.rename(columns={"date": "Date"}, inplace=True)

In [7]:
df5["Date"] = pd.to_datetime(df5["Date"])
df5["Date"] = df5["Date"].dt.normalize()

In [8]:
df5

            Date      open      high       low     close  volume
0     2015-01-09   8300.60   8317.25   8300.60   8307.50       0
1     2015-01-09   8307.50   8308.55   8290.90   8297.00       0
2     2015-01-09   8298.30   8298.85   8288.25   8296.05       0
3     2015-01-09   8296.05   8300.65   8288.45   8294.75       0
4     2015-01-09   8294.75   8304.50   8292.00   8304.00       0
...          ...       ...       ...       ...       ...     ...
68044 2026-01-22  25860.25  25860.25  25860.25  25860.25       0
68045 2026-01-22  25860.25  25860.25  25860.25  25860.25       0
68046 2026-01-22  25860.25  25860.25  25860.25  25860.25       0
68047 2026-01-22  25860.25  25860.25  25860.25  25860.25       0
68048 2026-01-22  25860.25  25860.25  25860.25  25860.25       0

[68049 rows x 6 columns]

In [9]:
df = df.drop('Adj Close', axis=1)
df

,Date,Open,High,Low,Close,Volume
0,2014-09-17,465.864014,468.174011,452.421997,457.334015,21056800
1,2014-09-18,456.859985,456.859985,413.104004,424.440002,34483200
2,2014-09-19,424.102997,427.834991,384.532013,394.795990,37919700
3,2014-09-20,394.673004,423.295990,389.882996,408.903992,36863600
4,2014-09-21,408.084991,412.425995,393.181000,398.821014,26580100
...,...,...,...,...,...,...
2708,2022-02-15,42586.464844,44667.218750,42491.035156,44575.203125,22721659051
2709,2022-02-16,44578.277344,44578.277344,43456.691406,43961.859375,19792547657
2710,2022-02-17,43937.070313,44132.972656,40249.371094,40538.011719,26246662813
2711,2022-02-18,40552.132813,40929.152344,39637.617188,40030.976563,23310007704
2712,2022-02-19,40022.132813,40246.027344,40010.867188,40126.429688,22263900160

In [10]:
df = df.rename(columns={
    'Open': 'Open_Price',
    'High': 'High_Price',
    'Low': 'Low_Price',
    'Close': 'Close_Price'
})

In [11]:
df["Asset_Name"] = "Bitcoin"
df["Asset_Type"] = "Crypto"
df["Sector"] = "Cryptocurrency"
df

,Date,Open_Price,High_Price,Low_Price,Close_Price,Volume,Asset_Name,Asset_Type,Sector
0,2014-09-17,465.864014,468.174011,452.421997,457.334015,21056800,Bitcoin,Crypto,Cryptocurrency
1,2014-09-18,456.859985,456.859985,413.104004,424.440002,34483200,Bitcoin,Crypto,Cryptocurrency
2,2014-09-19,424.102997,427.834991,384.532013,394.795990,37919700,Bitcoin,Crypto,Cryptocurrency
3,2014-09-20,394.673004,423.295990,389.882996,408.903992,36863600,Bitcoin,Crypto,Cryptocurrency
4,2014-09-21,408.084991,412.425995,393.181000,398.821014,26580100,Bitcoin,Crypto,Cryptocurrency
...,...,...,...,...,...,...,...,...,...
2708,2022-02-15,42586.464844,44667.218750,42491.035156,44575.203125,22721659051,Bitcoin,Crypto,Cryptocurrency
2709,2022-02-16,44578.277344,44578.277344,43456.691406,43961.859375,19792547657,Bitcoin,Crypto,Cryptocurrency
2710,2022-02-17,43937.070313,44132.972656,40249.371094,40538.011719,26246662813,Bitcoin,Crypto,Cryptocurrency
2711,2022-02-18,40552.132813,40929.152344,39637.617188,40030.976563,23310007704,Bitcoin,Crypto,Cryptocurrency
2712,2022-02-19,40022.132813,40246.027344,40010.867188,40126.429688,22263900160,Bitcoin,Crypto,Cryptocurrency

In [12]:
cols_to_drop1 = [
    "Adj Close","MA_20",	"MA_50",	"MA_200","Year","Month","Day_of_Week",	"Quarter"
]

# Dropping the columns
df4 = df4.drop(columns=cols_to_drop1)

# Checking the new shape to confirm they are gone
print(f"New shape: {df4.shape}")
df4.head()

New shape: (2511, 8)

,Date,Close,High,Low,Open,Volume,Daily_Return,Volatility_20
0,29-01-2016,106.949997,107.000000,106.260002,106.610001,8098700,NaN,NaN
1,01-02-2016,108.050003,108.150002,107.529999,107.540001,10471800,1.028524,NaN
2,02-02-2016,108.089996,108.180000,107.349998,107.919998,6656000,0.037014,NaN
3,03-02-2016,109.250000,109.580002,107.900002,107.910004,15785200,1.073183,NaN
4,04-02-2016,110.570000,110.699997,109.919998,110.449997,13213700,1.208238,NaN

In [13]:
df4.rename(columns={
    "Open": "Open_Price",
    "High": "High_Price",
    "Low": "Low_Price",
    "Close": "Close_Price",
    "Volatility_20": "Volatility"
}, inplace=True)

In [14]:
df4["Asset_Name"] = "Gold"
df4["Asset_Type"] = "Commodity"
df4["Sector"] = "Precious Metal"

In [15]:
df5.rename(columns={
    "open": "Open_Price",
    "high": "High_Price",
    "low": "Low_Price",
    "close": "Close_Price",
    "volume": "Volume"
}, inplace=True)

df5["Asset_Name"] = "BankNifty"   
df5["Asset_Type"] = "Index"            
df5["Sector"] = "Market Index"

In [16]:
mean_value = df4['Volatility'].mean()
df4['Volatility'] = df4['Volatility'].fillna(mean_value)

In [17]:
df4

,Date,Close_Price,High_Price,Low_Price,Open_Price,Volume,Daily_Return,Volatility,Asset_Name,Asset_Type,Sector
0,29-01-2016,106.949997,107.000000,106.260002,106.610001,8098700,NaN,0.871612,Gold,Commodity,Precious Metal
1,01-02-2016,108.050003,108.150002,107.529999,107.540001,10471800,1.028524,0.871612,Gold,Commodity,Precious Metal
2,02-02-2016,108.089996,108.180000,107.349998,107.919998,6656000,0.037014,0.871612,Gold,Commodity,Precious Metal
3,03-02-2016,109.250000,109.580002,107.900002,107.910004,15785200,1.073183,0.871612,Gold,Commodity,Precious Metal
4,04-02-2016,110.570000,110.699997,109.919998,110.449997,13213700,1.208238,0.871612,Gold,Commodity,Precious Metal
...,...,...,...,...,...,...,...,...,...,...,...
2506,16-01-2026,421.290008,424.799988,417.040008,422.799988,20951600,-0.481888,1.482148,Gold,Commodity,Precious Metal
2507,20-01-2026,437.230011,438.140015,434.100006,436.690002,21308100,3.783617,1.670545,Gold,Commodity,Precious Metal
2508,21-01-2026,443.600006,448.000000,437.109985,446.869995,38830200,1.456898,1.682109,Gold,Commodity,Precious Metal
2509,22-01-2026,451.790008,452.980011,443.559998,443.839996,19251200,1.846258,1.659640,Gold,Commodity,Precious Metal
2510,23-01-2026,458.000000,458.750000,453.450012,454.109985,21497000,1.374530,1.660933,Gold,Commodity,Precious Metal

In [18]:
df4.isnull().sum()

Date            0
Close_Price     0
High_Price      0
Low_Price       0
Open_Price      0
Volume          0
Daily_Return    1
Volatility      0
Asset_Name      0
Asset_Type      0
Sector          0
dtype: int64

In [19]:
df5

,Date,Open_Price,High_Price,Low_Price,Close_Price,Volume,Asset_Name,Asset_Type,Sector
0,2015-01-09,8300.60,8317.25,8300.60,8307.50,0,BankNifty,Index,Market Index
1,2015-01-09,8307.50,8308.55,8290.90,8297.00,0,BankNifty,Index,Market Index
2,2015-01-09,8298.30,8298.85,8288.25,8296.05,0,BankNifty,Index,Market Index
3,2015-01-09,8296.05,8300.65,8288.45,8294.75,0,BankNifty,Index,Market Index
4,2015-01-09,8294.75,8304.50,8292.00,8304.00,0,BankNifty,Index,Market Index
...,...,...,...,...,...,...,...,...,...
68044,2026-01-22,25860.25,25860.25,25860.25,25860.25,0,BankNifty,Index,Market Index
68045,2026-01-22,25860.25,25860.25,25860.25,25860.25,0,BankNifty,Index,Market Index
68046,2026-01-22,25860.25,25860.25,25860.25,25860.25,0,BankNifty,Index,Market Index
68047,2026-01-22,25860.25,25860.25,25860.25,25860.25,0,BankNifty,Index,Market Index
68048,2026-01-22,25860.25,25860.25,25860.25,25860.25,0,BankNifty,Index,Market Index

In [20]:
df = df.drop(df.index[:1983]).reset_index(drop=True)

print(f"New number of rows: {len(df)}")

New number of rows: 730

In [21]:
df5 = df5.drop(df5.index[:67319]).reset_index(drop=True)

print(f"New number of rows: {len(df)}")

New number of rows: 730

In [22]:
df5

,Date,Open_Price,High_Price,Low_Price,Close_Price,Volume,Asset_Name,Asset_Type,Sector
0,2025-12-11,26315.95,26345.55,26309.15,26333.60,0,BankNifty,Index,Market Index
1,2025-12-11,26334.25,26351.30,26300.95,26300.95,0,BankNifty,Index,Market Index
2,2025-12-11,26301.25,26310.70,26271.35,26304.45,0,BankNifty,Index,Market Index
3,2025-12-11,26304.55,26338.15,26298.00,26329.25,0,BankNifty,Index,Market Index
4,2025-12-11,26329.35,26344.25,26320.10,26340.75,0,BankNifty,Index,Market Index
...,...,...,...,...,...,...,...,...,...
725,2026-01-22,25860.25,25860.25,25860.25,25860.25,0,BankNifty,Index,Market Index
726,2026-01-22,25860.25,25860.25,25860.25,25860.25,0,BankNifty,Index,Market Index
727,2026-01-22,25860.25,25860.25,25860.25,25860.25,0,BankNifty,Index,Market Index
728,2026-01-22,25860.25,25860.25,25860.25,25860.25,0,BankNifty,Index,Market Index
729,2026-01-22,25860.25,25860.25,25860.25,25860.25,0,BankNifty,Index,Market Index

In [23]:
df4 = df4.drop(df4.index[:1781]).reset_index(drop=True)

print(f"New number of rows: {len(df)}")
df4

New number of rows: 730

,Date,Close_Price,High_Price,Low_Price,Open_Price,Volume,Daily_Return,Volatility,Asset_Name,Asset_Type,Sector
0,27-02-2023,169.009995,169.229996,168.550003,168.880005,4509200,0.392033,0.855431,Gold,Commodity,Precious Metal
1,28-02-2023,169.779999,170.250000,168.589996,168.779999,6761600,0.455597,0.871538,Gold,Commodity,Precious Metal
2,01-03-2023,170.759995,171.490005,170.470001,170.949997,6590500,0.577215,0.880761,Gold,Commodity,Precious Metal
3,02-03-2023,170.660004,170.979996,170.360001,170.520004,3950700,-0.058556,0.808767,Gold,Commodity,Precious Metal
4,03-03-2023,172.490005,172.600006,170.979996,171.449997,6894500,1.072309,0.751174,Gold,Commodity,Precious Metal
...,...,...,...,...,...,...,...,...,...,...,...
725,16-01-2026,421.290008,424.799988,417.040008,422.799988,20951600,-0.481888,1.482148,Gold,Commodity,Precious Metal
726,20-01-2026,437.230011,438.140015,434.100006,436.690002,21308100,3.783617,1.670545,Gold,Commodity,Precious Metal
727,21-01-2026,443.600006,448.000000,437.109985,446.869995,38830200,1.456898,1.682109,Gold,Commodity,Precious Metal
728,22-01-2026,451.790008,452.980011,443.559998,443.839996,19251200,1.846258,1.659640,Gold,Commodity,Precious Metal
729,23-01-2026,458.000000,458.750000,453.450012,454.109985,21497000,1.374530,1.660933,Gold,Commodity,Precious Metal

In [24]:
df5.sample(2)

,Date,Open_Price,High_Price,Low_Price,Close_Price,Volume,Asset_Name,Asset_Type,Sector
287,2025-12-29,26488.85,26490.7,26471.0,26482.3,0,BankNifty,Index,Market Index
686,2026-01-21,25787.10,25790.7,25747.9,25758.5,0,BankNifty,Index,Market Index

In [25]:
df5['Date'] = pd.to_datetime(df5['Date'])
df['Date'] = pd.to_datetime(df['Date'])
df4['Date'] = pd.to_datetime(df4['Date'])

C:\Users\Raj Upadhyay\AppData\Local\Temp\ipykernel_27112\106444123.py:3: UserWarning: Parsing dates in DD/MM/YYYY format when dayfirst=False (the default) was specified. This may lead to inconsistently parsed dates! Specify a format to ensure consistent parsing.
  df4['Date'] = pd.to_datetime(df4['Date'])

In [26]:
df.sample(2)

,Date,Open_Price,High_Price,Low_Price,Close_Price,Volume,Asset_Name,Asset_Type,Sector
142,2020-07-12,9241.054688,9319.418945,9197.450195,9276.500000,14452361907,Bitcoin,Crypto,Cryptocurrency
349,2021-02-04,37475.105469,38592.175781,36317.500000,36926.066406,68838074392,Bitcoin,Crypto,Cryptocurrency

In [27]:
df4.sample(2)

,Date,Close_Price,High_Price,Low_Price,Open_Price,Volume,Daily_Return,Volatility,Asset_Name,Asset_Type,Sector
2,2023-01-03,170.759995,171.490005,170.470001,170.949997,6590500,0.577215,0.880761,Gold,Commodity,Precious Metal
338,2024-02-07,215.559998,216.080002,214.619995,215.330002,4921700,-0.004643,1.165324,Gold,Commodity,Precious Metal

In [28]:
df4.sample(2)

,Date,Close_Price,High_Price,Low_Price,Open_Price,Volume,Daily_Return,Volatility,Asset_Name,Asset_Type,Sector
700,2025-10-12,389.049988,389.760010,384.500000,385.950012,9120500,0.425915,0.858354,Gold,Commodity,Precious Metal
422,2024-10-30,257.500000,257.709992,255.910004,256.760010,6386200,0.550589,0.657882,Gold,Commodity,Precious Metal

In [29]:
df["Profit"] = df["Close_Price"] - df["Open_Price"]

df["Daily_Return"] = df["Profit"] / df["Open_Price"]

In [30]:
df4["Profit"] = df4["Close_Price"] - df4["Open_Price"]

df4["Daily_Return"] = df4["Profit"] / df4["Open_Price"]

In [31]:
df4.sample(2)

,Date,Close_Price,High_Price,Low_Price,Open_Price,Volume,Daily_Return,Volatility,Asset_Name,Asset_Type,Sector,Profit
35,2023-04-18,186.250000,186.990005,185.039993,185.240005,8056900,0.005452,1.101839,Gold,Commodity,Precious Metal,1.009995
227,2024-01-23,187.949997,188.149994,187.279999,187.449997,5040800,0.002667,0.603363,Gold,Commodity,Precious Metal,0.500000

In [32]:
df5["Profit"] = df5["Close_Price"] - df5["Open_Price"]

df5["Daily_Return"] = df5["Profit"] / df5["Open_Price"]

In [33]:
df5.sample(2)

,Date,Open_Price,High_Price,Low_Price,Close_Price,Volume,Asset_Name,Asset_Type,Sector,Profit,Daily_Return
265,2025-12-26,26594.15,26597.35,26567.45,26575.1,0,BankNifty,Index,Market Index,-19.05,-0.000716
135,2025-12-18,26390.65,26396.25,26381.05,26387.3,0,BankNifty,Index,Market Index,-3.35,-0.000127

In [34]:
df_final=pd.concat([df5,df,df4],ignore_index=True)
df_final

,Date,Open_Price,High_Price,Low_Price,Close_Price,Volume,Asset_Name,Asset_Type,Sector,Profit,Daily_Return,Volatility
0,2025-12-11,26315.950000,26345.550000,26309.150000,26333.600000,0,BankNifty,Index,Market Index,17.650000,0.000671,NaN
1,2025-12-11,26334.250000,26351.300000,26300.950000,26300.950000,0,BankNifty,Index,Market Index,-33.300000,-0.001265,NaN
2,2025-12-11,26301.250000,26310.700000,26271.350000,26304.450000,0,BankNifty,Index,Market Index,3.200000,0.000122,NaN
3,2025-12-11,26304.550000,26338.150000,26298.000000,26329.250000,0,BankNifty,Index,Market Index,24.700000,0.000939,NaN
4,2025-12-11,26329.350000,26344.250000,26320.100000,26340.750000,0,BankNifty,Index,Market Index,11.400000,0.000433,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
2185,2026-01-16,422.799988,424.799988,417.040008,421.290008,20951600,Gold,Commodity,Precious Metal,-1.509979,-0.003571,1.482148
2186,2026-01-20,436.690002,438.140015,434.100006,437.230011,21308100,Gold,Commodity,Precious Metal,0.540009,0.001237,1.670545
2187,2026-01-21,446.869995,448.000000,437.109985,443.600006,38830200,Gold,Commodity,Precious Metal,-3.269989,-0.007318,1.682109
2188,2026-01-22,443.839996,452.980011,443.559998,451.790008,19251200,Gold,Commodity,Precious Metal,7.950012,0.017912,1.659640
2189,2026-01-23,454.109985,458.750000,453.450012,458.000000,21497000,Gold,Commodity,Precious Metal,3.890015,0.008566,1.660933

In [35]:
df_final

,Date,Open_Price,High_Price,Low_Price,Close_Price,Volume,Asset_Name,Asset_Type,Sector,Profit,Daily_Return,Volatility
0,2025-12-11,26315.950000,26345.550000,26309.150000,26333.600000,0,BankNifty,Index,Market Index,17.650000,0.000671,NaN
1,2025-12-11,26334.250000,26351.300000,26300.950000,26300.950000,0,BankNifty,Index,Market Index,-33.300000,-0.001265,NaN
2,2025-12-11,26301.250000,26310.700000,26271.350000,26304.450000,0,BankNifty,Index,Market Index,3.200000,0.000122,NaN
3,2025-12-11,26304.550000,26338.150000,26298.000000,26329.250000,0,BankNifty,Index,Market Index,24.700000,0.000939,NaN
4,2025-12-11,26329.350000,26344.250000,26320.100000,26340.750000,0,BankNifty,Index,Market Index,11.400000,0.000433,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
2185,2026-01-16,422.799988,424.799988,417.040008,421.290008,20951600,Gold,Commodity,Precious Metal,-1.509979,-0.003571,1.482148
2186,2026-01-20,436.690002,438.140015,434.100006,437.230011,21308100,Gold,Commodity,Precious Metal,0.540009,0.001237,1.670545
2187,2026-01-21,446.869995,448.000000,437.109985,443.600006,38830200,Gold,Commodity,Precious Metal,-3.269989,-0.007318,1.682109
2188,2026-01-22,443.839996,452.980011,443.559998,451.790008,19251200,Gold,Commodity,Precious Metal,7.950012,0.017912,1.659640
2189,2026-01-23,454.109985,458.750000,453.450012,458.000000,21497000,Gold,Commodity,Precious Metal,3.890015,0.008566,1.660933

In [36]:
df_final.isnull().sum()

Date               0
Open_Price         0
High_Price         0
Low_Price          0
Close_Price        0
Volume             0
Asset_Name         0
Asset_Type         0
Sector             0
Profit             0
Daily_Return       0
Volatility      1460
dtype: int64

In [37]:
df_final.drop('Volatility', axis=1, inplace=True)

In [38]:
df_final

,Date,Open_Price,High_Price,Low_Price,Close_Price,Volume,Asset_Name,Asset_Type,Sector,Profit,Daily_Return
0,2025-12-11,26315.950000,26345.550000,26309.150000,26333.600000,0,BankNifty,Index,Market Index,17.650000,0.000671
1,2025-12-11,26334.250000,26351.300000,26300.950000,26300.950000,0,BankNifty,Index,Market Index,-33.300000,-0.001265
2,2025-12-11,26301.250000,26310.700000,26271.350000,26304.450000,0,BankNifty,Index,Market Index,3.200000,0.000122
3,2025-12-11,26304.550000,26338.150000,26298.000000,26329.250000,0,BankNifty,Index,Market Index,24.700000,0.000939
4,2025-12-11,26329.350000,26344.250000,26320.100000,26340.750000,0,BankNifty,Index,Market Index,11.400000,0.000433
...,...,...,...,...,...,...,...,...,...,...,...
2185,2026-01-16,422.799988,424.799988,417.040008,421.290008,20951600,Gold,Commodity,Precious Metal,-1.509979,-0.003571
2186,2026-01-20,436.690002,438.140015,434.100006,437.230011,21308100,Gold,Commodity,Precious Metal,0.540009,0.001237
2187,2026-01-21,446.869995,448.000000,437.109985,443.600006,38830200,Gold,Commodity,Precious Metal,-3.269989,-0.007318
2188,2026-01-22,443.839996,452.980011,443.559998,451.790008,19251200,Gold,Commodity,Precious Metal,7.950012,0.017912
2189,2026-01-23,454.109985,458.750000,453.450012,458.000000,21497000,Gold,Commodity,Precious Metal,3.890015,0.008566

In [39]:
df_final.isnull().sum()

Date            0
Open_Price      0
High_Price      0
Low_Price       0
Close_Price     0
Volume          0
Asset_Name      0
Asset_Type      0
Sector          0
Profit          0
Daily_Return    0
dtype: int64

In [40]:
print(df["Asset_Type"].value_counts())

Crypto    730
Name: Asset_Type, dtype: int64

In [41]:
print(df["Asset_Type"].value_counts())

Crypto    730
Name: Asset_Type, dtype: int64

In [42]:
print(df["Asset_Type"].value_counts())

Crypto    730
Name: Asset_Type, dtype: int64

In [43]:
df_final["Asset_Type"].value_counts()

Index        730
Crypto       730
Commodity    730
Name: Asset_Type, dtype: int64

In [44]:
df_final.sample(2)
df_final.isnull().sum()

Date            0
Open_Price      0
High_Price      0
Low_Price       0
Close_Price     0
Volume          0
Asset_Name      0
Asset_Type      0
Sector          0
Profit          0
Daily_Return    0
dtype: int64

In [45]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier

# 1. Setup Data (Only your 4 features)
features = ["Open_Price", "High_Price", "Low_Price", "Volume"]
X_raw = df_final[features].copy()
y_raw = df_final["Asset_Type"].copy()

# 2. Transform to % Change (Crucial for realistic 0.80 accuracy)
X = X_raw.pct_change().replace([np.inf, -np.inf], np.nan).dropna()
y = y_raw.iloc[X.index] # Keep y aligned with X after dropping NaNs

# 3. Encode Target
le = LabelEncoder()
y_encoded = le.fit_transform(y)

# 4. Split
X_train, X_test, y_train, y_test = train_test_split(
    X, y_encoded, test_size=0.2, random_state=42, stratify=y_encoded
)

# 5. Train Model
model = RandomForestClassifier(n_estimators=100, max_depth=5, random_state=42)
model.fit(X_train, y_train)

# 6. Results
acc = model.score(X_test, y_test)
print(f"Realistic Accuracy: {acc:.4f}")

# -----------------------------
# 7. QUICK TESTER (Single Input)
# -----------------------------
def predict_now(open_p, high_p, low_p, vol):
    # This simulates a small % change for a single prediction
    test_data = np.array([[(high_p-open_p)/open_p, (high_p-low_p)/low_p, (low_p-open_p)/open_p, 0.02]])
    pred = model.predict(test_data)[0]
    return le.inverse_transform([pred])[0]

# Example test
print("Prediction Test:", predict_now(50000, 51000, 49500, 100000))

Realistic Accuracy: 0.8390
Prediction Test: Crypto

C:\Users\Raj Upadhyay\.vscode\cli\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

In [46]:
df_final.sample(5)

,Date,Open_Price,High_Price,Low_Price,Close_Price,Volume,Asset_Name,Asset_Type,Sector,Profit,Daily_Return
5,2025-12-11,26340.750000,26358.950000,26326.950000,26353.550000,0,BankNifty,Index,Market Index,12.800000,0.000486
119,2025-12-17,26342.750000,26351.500000,26333.650000,26339.950000,0,BankNifty,Index,Market Index,-2.800000,-0.000106
1194,2021-05-30,34607.406250,36400.667969,33520.738281,35678.128906,31646080921,Bitcoin,Crypto,Cryptocurrency,1070.722656,0.030939
1420,2022-01-11,41819.507813,43001.156250,41407.753906,42735.855469,26327648900,Bitcoin,Crypto,Cryptocurrency,916.347656,0.021912
805,2020-05-06,9007.441406,9411.467773,8966.706055,9268.761719,49371886931,Bitcoin,Crypto,Cryptocurrency,261.320313,0.029012

In [47]:
import numpy as np

df_final["Volume"] = np.log1p(df_final["Volume"])

In [48]:
df_final.isnull().sum()

Date            0
Open_Price      0
High_Price      0
Low_Price       0
Close_Price     0
Volume          0
Asset_Name      0
Asset_Type      0
Sector          0
Profit          0
Daily_Return    0
dtype: int64

In [49]:
print(df["Volume"].describe())

count    7.300000e+02
mean     3.975794e+10
std      2.083812e+10
min      1.225260e+10
25%      2.672666e+10
50%      3.585267e+10
75%      4.753591e+10
max      3.509679e+11
Name: Volume, dtype: float64

In [50]:
df_final.sample(5)

,Date,Open_Price,High_Price,Low_Price,Close_Price,Volume,Asset_Name,Asset_Type,Sector,Profit,Daily_Return
1229,2021-07-04,34665.566406,35937.566406,34396.476563,35287.781250,23.939109,Bitcoin,Crypto,Cryptocurrency,622.214844,0.017949
220,2025-12-24,26713.750000,26764.750000,26676.800000,26761.000000,0.000000,BankNifty,Index,Market Index,47.250000,0.001769
1679,2024-10-01,188.139999,188.440002,187.210007,187.500000,15.320632,Gold,Commodity,Precious Metal,-0.639999,-0.003402
611,2026-01-16,26305.600000,26312.750000,26248.450000,26286.100000,0.000000,BankNifty,Index,Market Index,-19.500000,-0.000741
1969,2025-10-03,267.619995,268.440002,265.640015,266.040008,15.842856,Gold,Commodity,Precious Metal,-1.579987,-0.005904

In [51]:
import pandas as pd

df4['Date'] = pd.to_datetime(df4['Date'])

df4 = df4[df4['Date'] >= pd.Timestamp.now() - pd.DateOffset(years=2)]

gold_avg = df[df['Asset_Name'] == 'Gold']['Daily_Return'].mean()
print(f"Gold avg daily return: {gold_avg:.4f}%")

Gold avg daily return: nan%

In [53]:

df = df_final.copy()
df = df.sort_values(["Asset_Name", "Date"])


df["MA_3"]  = df.groupby("Asset_Name")["Close_Price"].transform(lambda x: x.rolling(3).mean())
df["MA_5"]  = df.groupby("Asset_Name")["Close_Price"].transform(lambda x: x.rolling(5).mean())
df["MA_10"] = df.groupby("Asset_Name")["Close_Price"].transform(lambda x: x.rolling(10).mean())



df["Volatility"] = df["High_Price"] - df["Low_Price"]

df["Volatility_5"] = df.groupby("Asset_Name")["Volatility"].transform(lambda x: x.rolling(5).mean())




df["Return_1"] = df.groupby("Asset_Name")["Close_Price"].pct_change()


df["Return_3"] = df.groupby("Asset_Name")["Close_Price"].pct_change(3)


df["Return_7"] = df.groupby("Asset_Name")["Close_Price"].pct_change(7)



df["Trend"] = (df["MA_3"] > df["MA_10"]).astype(int)



df["Momentum"] = df["Close_Price"] - df.groupby("Asset_Name")["Close_Price"].shift(3)



df = df.dropna()

print("✅ Feature engineering done")
print(df.head())

✅ Feature engineering done
         Date  Open_Price  High_Price  Low_Price  Close_Price  Volume  \
9  2025-12-11    26413.40    26413.75   26386.40     26387.20     0.0
10 2025-12-11    26387.25    26396.30   26344.80     26360.50     0.0
11 2025-12-11    26359.55    26377.10   26358.30     26368.00     0.0
12 2025-12-11    26367.00    26396.85   26367.00     26381.75     0.0
13 2025-12-11    26381.65    26406.50   26377.55     26396.15     0.0

   Asset_Name Asset_Type        Sector  Profit  ...          MA_3      MA_5  \
9   BankNifty      Index  Market Index  -26.20  ...  26403.900000  26390.75
10  BankNifty      Index  Market Index  -26.75  ...  26386.350000  26392.14
11  BankNifty      Index  Market Index    8.45  ...  26371.900000  26388.04
12  BankNifty      Index  Market Index   14.75  ...  26370.083333  26381.76
13  BankNifty      Index  Market Index   14.50  ...  26381.966667  26378.72

        MA_10  Volatility  Volatility_5  Return_1  Return_3  Return_7  Trend  \
9   26356.275       27.35         35.40 -0.000914 -0.000049  0.003146      1
10  26358.965       51.50         39.30 -0.001012 -0.001993  0.001187      1
11  26365.670       18.80         34.02  0.000285 -0.001641  0.001035      1
12  26373.400       29.85         31.40  0.000521 -0.000207  0.001070      0
13  26380.090       28.95         31.29  0.000546  0.001352  0.000290      1

    Momentum
9      -1.30
10    -52.65
11    -43.35
12     -5.45
13     35.65

[5 rows x 21 columns]

In [54]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, r2_score


df = df_final.copy()
df.columns = df.columns.str.strip()


df = df.drop(["Profit", "Asset_Type", "Sector"], axis=1)

df["Date"] = pd.to_datetime(df["Date"])

df = df.sort_values(["Asset_Name", "Date"])



df["MA_3"]  = df.groupby("Asset_Name")["Close_Price"].transform(lambda x: x.rolling(3).mean())
df["MA_5"]  = df.groupby("Asset_Name")["Close_Price"].transform(lambda x: x.rolling(5).mean())
df["MA_10"] = df.groupby("Asset_Name")["Close_Price"].transform(lambda x: x.rolling(10).mean())

df["Volatility"] = df["High_Price"] - df["Low_Price"]
df["Volatility_5"] = df.groupby("Asset_Name")["Volatility"].transform(lambda x: x.rolling(5).mean())

df["Return_1"] = df.groupby("Asset_Name")["Close_Price"].pct_change()
df["Return_3"] = df.groupby("Asset_Name")["Close_Price"].pct_change(3)
df["Return_7"] = df.groupby("Asset_Name")["Close_Price"].pct_change(7)

# Trend
df["Trend"] = (df["MA_3"] > df["MA_10"]).astype(int)

# Momentum
df["Momentum"] = df["Close_Price"] - df.groupby("Asset_Name")["Close_Price"].shift(3)


df["Target"] = df.groupby("Asset_Name")["Daily_Return"].shift(-1)


df = df.dropna()

 
 
FEATURES = [
    "Open_Price", "High_Price", "Low_Price", "Close_Price", "Volume",
    "MA_3", "MA_5", "MA_10",
    "Volatility", "Volatility_5",
    "Return_1", "Return_3", "Return_7",
    "Trend", "Momentum"
]

X = df[FEATURES]
y = df["Target"]


X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, shuffle=False
)


model = RandomForestRegressor(
    n_estimators=200,
    max_depth=8,
    random_state=42
)

model.fit(X_train, y_train)

preds = model.predict(X_test)

print("MAE:", mean_absolute_error(y_test, preds))
print("R2 Score:", r2_score(y_test, preds))


def predict_investment(asset_name, investment=200, days=20):

    asset_df = df[df["Asset_Name"] == asset_name].sort_values("Date")

    if asset_df.empty:
        print(f"No data for {asset_name}")
        return

    latest = asset_df.iloc[[-1]][FEATURES]

    # Predict daily return
    daily_return = model.predict(latest)[0]

    # Convert to final money
    final_amount = investment * ((1 + daily_return) ** days)
    profit = final_amount - investment

    print("\n========== RESULT ==========")
    print(f"Asset: {asset_name}")
    print(f"Investment: ₹{investment}")
    print(f"Days: {days}")
    print(f"Predicted Daily Return: {daily_return:.4f}")
    print(f"Final Amount: ₹{final_amount:.2f}")
    print(f"Profit: ₹{profit:.2f}")
    print("============================")

    return final_amount



predict_investment("Gold", 200, 20)
predict_investment("BankNifty", 200, 20)

MAE: 0.005365623709034936
R2 Score: -0.3628172049176732

========== RESULT ==========
Asset: Gold
Investment: ₹200
Days: 20
Predicted Daily Return: 0.0001
Final Amount: ₹200.21
Profit: ₹0.21
============================

========== RESULT ==========
Asset: BankNifty
Investment: ₹200
Days: 20
Predicted Daily Return: 0.0004
Final Amount: ₹201.40
Profit: ₹1.40
============================

201.40496664679512

In [55]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, r2_score


df = df_final.copy()
df.columns = df.columns.str.strip()


df = df.drop(["Profit", "Asset_Type", "Sector"], axis=1)

df["Date"] = pd.to_datetime(df["Date"])
df = df.sort_values(["Asset_Name", "Date"])




df["MA_3"]  = df.groupby("Asset_Name")["Close_Price"].transform(lambda x: x.rolling(3).mean())
df["MA_5"]  = df.groupby("Asset_Name")["Close_Price"].transform(lambda x: x.rolling(5).mean())
df["MA_10"] = df.groupby("Asset_Name")["Close_Price"].transform(lambda x: x.rolling(10).mean())

# Volatility
df["Volatility"] = df["High_Price"] - df["Low_Price"]
df["Volatility_5"] = df.groupby("Asset_Name")["Volatility"].transform(lambda x: x.rolling(5).mean())

# Returns (momentum)
df["Return_1"] = df.groupby("Asset_Name")["Close_Price"].pct_change()
df["Return_3"] = df.groupby("Asset_Name")["Close_Price"].pct_change(3)
df["Return_5"] = df.groupby("Asset_Name")["Close_Price"].pct_change(5)

# Trend
df["Trend"] = (df["MA_3"] > df["MA_10"]).astype(int)

# Momentum
df["Momentum"] = df["Close_Price"] - df.groupby("Asset_Name")["Close_Price"].shift(3)


PREDICT_DAYS = 5

df["Target"] = df.groupby("Asset_Name")["Daily_Return"].transform(
    lambda x: x.shift(-1).rolling(PREDICT_DAYS).sum().shift(-(PREDICT_DAYS - 1))
)


df = df.dropna()


# 
FEATURES = [
    "Open_Price", "High_Price", "Low_Price", "Close_Price", "Volume",
    "MA_3", "MA_5", "MA_10",
    "Volatility", "Volatility_5",
    "Return_1", "Return_3", "Return_5",
    "Trend", "Momentum"
]

X = df[FEATURES]
y = df["Target"]

#
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, shuffle=False
)


model = RandomForestRegressor(
    n_estimators=200,
    max_depth=8,
    random_state=42
)

model.fit(X_train, y_train)

# -----------------------------
preds = model.predict(X_test)

print("MAE:", mean_absolute_error(y_test, preds))
print("R2 Score:", r2_score(y_test, preds))



def predict_investment(asset_name, investment=200, days=5):

    asset_df = df[df["Asset_Name"] == asset_name].sort_values("Date")

    if asset_df.empty:
        print(f"No data for {asset_name}")
        return

    latest = asset_df.iloc[[-1]][FEATURES]

    predicted_return = model.predict(latest)[0]

    # convert to final money
    final_amount = investment * (1 + predicted_return)
    profit = final_amount - investment

    print("\n===== RESULT =====")
    print(f"Asset: {asset_name}")
    print(f"Investment: ₹{investment}")
    print(f"Days: {days}")
    print(f"Predicted 5-day Return: {predicted_return:.4f}")
    print(f"Final Amount: ₹{final_amount:.2f}")
    print(f"Profit: ₹{profit:.2f}")
    print("==================")

    return final_amount



predict_investment("Gold", 200, 5)
predict_investment("BankNifty", 200, 5)

MAE: 0.010966405471934209
R2 Score: -0.023335729160788077

===== RESULT =====
Asset: Gold
Investment: ₹200
Days: 5
Predicted 5-day Return: 0.0031
Final Amount: ₹200.63
Profit: ₹0.63
==================

===== RESULT =====
Asset: BankNifty
Investment: ₹200
Days: 5
Predicted 5-day Return: 0.0005
Final Amount: ₹200.11
Profit: ₹0.11
==================

200.1053313165475

In [56]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, r2_score


df = df_final.copy()
df.columns = df.columns.str.strip()


df = df.drop(["Profit", "Asset_Type", "Sector"], axis=1)

df["Date"] = pd.to_datetime(df["Date"])
df = df.sort_values(["Asset_Name", "Date"])




df["MA_5"]  = df.groupby("Asset_Name")["Close_Price"].transform(lambda x: x.rolling(5).mean())
df["MA_10"] = df.groupby("Asset_Name")["Close_Price"].transform(lambda x: x.rolling(10).mean())
df["MA_20"] = df.groupby("Asset_Name")["Close_Price"].transform(lambda x: x.rolling(20).mean())


df["Volatility"] = df["High_Price"] - df["Low_Price"]
df["Volatility_10"] = df.groupby("Asset_Name")["Volatility"].transform(lambda x: x.rolling(10).mean())

df["Return_1"]  = df.groupby("Asset_Name")["Close_Price"].pct_change()
df["Return_5"]  = df.groupby("Asset_Name")["Close_Price"].pct_change(5)
df["Return_10"] = df.groupby("Asset_Name")["Close_Price"].pct_change(10)


df["Trend"] = (df["MA_5"] > df["MA_20"]).astype(int)


df["Momentum"] = df["Close_Price"] - df.groupby("Asset_Name")["Close_Price"].shift(5)


PREDICT_DAYS = 20

df["Target"] = df.groupby("Asset_Name")["Daily_Return"].transform(
    lambda x: x.shift(-1).rolling(PREDICT_DAYS).sum().shift(-(PREDICT_DAYS - 1))
)


df = df.dropna()


FEATURES = [
    "Open_Price", "High_Price", "Low_Price", "Close_Price", "Volume",
    "MA_5", "MA_10", "MA_20",
    "Volatility", "Volatility_10",
    "Return_1", "Return_5", "Return_10",
    "Trend", "Momentum"
]

X = df[FEATURES]
y = df["Target"]


X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, shuffle=False
)


model = RandomForestRegressor(
    n_estimators=200,
    max_depth=8,
    random_state=42
)

model.fit(X_train, y_train)

-
preds = model.predict(X_test)

print("MAE:", mean_absolute_error(y_test, preds))
print("R2 Score:", r2_score(y_test, preds))



def predict_investment(asset_name, investment=200, days=20):

    asset_df = df[df["Asset_Name"] == asset_name].sort_values("Date")

    if asset_df.empty:
        print(f"No data for {asset_name}")
        return

    latest = asset_df.iloc[[-1]][FEATURES]

    predicted_return = model.predict(latest)[0]

    final_amount = investment * (1 + predicted_return)
    profit = final_amount - investment

    print("\n===== RESULT =====")
    print(f"Asset: {asset_name}")
    print(f"Investment: ₹{investment}")
    print(f"Days: {days}")
    print(f"Predicted 20-day Return: {predicted_return:.4f}")
    print(f"Final Amount: ₹{final_amount:.2f}")
    print(f"Profit: ₹{profit:.2f}")
    print("==================")

    return final_amount



predict_investment("Gold", 200, 20)
predict_investment("BankNifty", 200, 20)

MAE: 0.020766276480826833
R2 Score: -0.1481132670195946

===== RESULT =====
Asset: Gold
Investment: ₹200
Days: 20
Predicted 20-day Return: 0.0060
Final Amount: ₹201.20
Profit: ₹1.20
==================

===== RESULT =====
Asset: BankNifty
Investment: ₹200
Days: 20
Predicted 20-day Return: -0.0012
Final Amount: ₹199.77
Profit: ₹-0.23
==================

199.76844797607342